<?php 
// This file is part of Stack - http://stack.bham.ac.uk//
//
// Stack is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Stack is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Stack.  If not, see <http://www.gnu.org/licenses/>.

function stack_string($key, $a = null) {
    return get_string($key, 'qtype_stack', $a);
}

function stack_generate_maximalocal() {
    global $CFG;
    
    //print_r($CFG);
    $settings = get_config('qtype_stack');
    
    $maxloc  = "/* ***********************************************************************/\n";
    $maxloc .= "/* This file is automatically generated at installation time.            */\n";
    $maxloc .= "/* The purpose is to transfer configuration settings to Maxima.          */\n";
    $maxloc .= "/* Hence, you should not edit this file.  Edit your configuration        */\n";
    $maxloc .= "/* This file is regularly overwritten, so your changes will be lost.     */\n";
    $maxloc .= "/* ***********************************************************************/\n\n";

    $maxloc .= "/* File generated on ".date("F j, Y, g:i a")." */\n\n";

    $dirroot = $CFG->dirroot;
    $root = new STACK_StringUtil($dirroot.'\question\type\stack\stack\maxima');
    $docroot = $root->convertSlashPaths();

    $maxloc .= "/* Add the location to Maxima's search path */\n";
    $maxloc .= "file_search_maxima:append( [sconcat(\"{$docroot}/###".'.{mac,mc}")] , file_search_maxima)$'."\n";
    $maxloc .= "file_search_lisp:append( [sconcat(\"{$docroot}/###".'.{lisp}")] , file_search_lisp)$'."\n";

    //add in the log directory to the search path
    $dataroot = $CFG->dataroot;
    $root = new STACK_StringUtil($dataroot.'/stack');
    $logs = $root->convertSlashPaths();
    $maxloc .= "file_search_maxima:append( [sconcat(\"{$logs}/###".'.{mac,mc}")] , file_search_maxima)$'."\n";
    $maxloc .= "file_search_lisp:append( [sconcat(\"{$logs}/###".'.{lisp}")] , file_search_lisp)$'."\n";

    $maxloc .="\n\nSTACK_SETUP(ex):=block(\n";
    $vnum = substr($settings->maximaversion,2);
    $maxloc .="    MAXIMA_VERSION_NUM:$vnum,\n";

    // Create an array of Maxima settings.
    // These are used by the GNUplot "set terminal" command.  Currently no user interface...
    $maximalocal['MAXIMA_VERSION'] = $settings->maximaversion;
    $maximalocal['PLOT_TERMINAL'] = 'png'; // 'gif' is not recommended.  See GNUPlot documentation.
    $maximalocal['PLOT_TERM_OPT'] = 'large transparent size 450,300';
    

    $platform = $settings->platform;
    // Windows
    if ('win' == $platform) {
        $maximalocal['DEL_CMD']       = 'del';
        if ($settings->plotcommand == 'gnuplot' or $settings->plotcommand == '') {
            // This does its best to find your version of Gnuplot...
            if ($vnum>25) {
                $maximalocal['GNUPLOT_CMD'] = '"c:/Program Files/Maxima-'.$settings->maximaversion.'-gcl/gnuplot/wgnuplot.exe"';
            } else if ($vnum>23) {
                $maximalocal['GNUPLOT_CMD'] = '"c:/Program Files/Maxima-'.$settings->maximaversion.'/gnuplot/wgnuplot.exe"';
            } else {
                $maximalocal['GNUPLOT_CMD'] = '"c:/Program Files/Maxima-'.$settings->maximaversion.'/bin/wgnuplot.exe"';
            }
        } else {
            $maximalocal['GNUPLOT_CMD'] = $settings->plotcommand;
        }
    } else {
        $maximalocal['DEL_CMD']       = "rm";
        $maximalocal['GNUPLOT_CMD' ]  = $settings->plotcommand;
    }
    $maximalocal['TMP_IMAGE_DIR'] = $path = $CFG->dataroot . '/stack/';
    //TODO where do we put plots properly?!
    $maximalocal['IMAGE_DIR']     = 'C:/xampp/htdocs/tmp/'; // $CFG->dataroot;
    $maximalocal['URL_BASE']      = 'http://localhost/tmp/'; //$CFG->wwwroot;

    // Loop over this array to format them correctly...
    foreach ($maximalocal as $var => $val) {
        if ('win' == $platform and 'URL_BASE' != $var ) {
            $val = addslashes(str_replace( '/', '\\', $val));
        }
        $maxloc .="    $var:\"$val\",\n";
    }

    $maxloc .="    true)$\n\n";
    $maxloc .= "/* Load the main libraries */\n";
    $maxloc .= "load(\"stackmaxima.mac\")\$\n";

    $fh = fopen($dataroot.'/stack/maximalocal.mac','w');
    if (false === $fh) {
       throw new Exception('Failed to write Maxima configuration file.');
    } else {
        fwrite($fh,$maxloc);
        //echo $maxloc;
        fclose($fh);
    }
    return true;
}
