<?php
// This file is part of Stack - http://stack.bham.ac.uk/
//
// Stack is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Stack is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Stack.  If not, see <http://www.gnu.org/licenses/>.

/**
 * This script runs the answers tests and verifies the results.
 *
 * This serves two purposes. First, it verifies that the answer tests are working
 * correctly, and second it serves to document the expected behaviour of answer
 * tests, which is useful for learning how they work.
 *
 * @copyright  2012 University of Birmingham
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */


class stack_answertest_test_data {
    const NAME    = 0;
    const OPTIONS = 1;
    const SANS    = 2;
    const TANS    = 3;
    const SCORE   = 4;
    const ANSNOTE = 5;
    const NOTES   = 6;

    /* Raw data should be in the following form.
     * Name of test
     * Student's answer
     * Teacher's answer
     * Expected result
     *    0 = different
     *    1 = same
     *    -1 = "Test fails", but this is trapped.
     * Test options
     * Header row in the table.
     */
    protected static $rawdata = array(
        array('AlgEquiv', '', '1/0', '1', -1, 'CASError: Division by zero.', ''),
        array('AlgEquiv', '', '1', '1/0', -1, 'CASError: Division by zero.', ''),
        array('AlgEquiv', '', 'x-1)^2', '(x-1)^2', -1, 'ATAlgEquiv_STACKERROR_SAns.', ''),
        array('AlgEquiv', '', 'integerp(3)', 'true', 1, '', 'Predicates'),
        array('AlgEquiv', '', 'integerp(3.1)', 'true', 0, '', ''),
        array('AlgEquiv', '', 'lowesttermsp(x^2/x)', 'true', 0, '', ''),
        array('AlgEquiv', '', 'lowesttermsp(-y/-x)', 'true', 0, '', ''),
        array('AlgEquiv', '', 'lowesttermsp((x^2-1)/(x-1))', 'true', 0, '', ''),
        array('AlgEquiv', '', 'lowesttermsp((x^2-1)/(x+2))', 'true', 1, '', ''),
        array('AlgEquiv', '', 'X', 'x', 0, 'ATAlgEquiv_WrongCase.', 'Case sensitivity'),
        array('AlgEquiv', '', 'Y=1+X', 'y=1+x', 0, 'ATEquation_default',
            'Permutations of variables (To do: a dedicated answer test with feedback)'),
        array('AlgEquiv', '', 'v+w+x+y+z', 'a+b+c+A+B', 0, '', ''),
        array('AlgEquiv', '', '4^(-1/2)', '1/2', 1, '', 'Numbers'),
        array('AlgEquiv', '', '4^(1/2)', 'sqrt(4)', 1, '', ''),
        array('AlgEquiv', '', '0.5', '1/2', 1, '', 'Mix of floats and rational numbers'),
        array('AlgEquiv', '', '0.33', '1/3', 0, '', ''),
        array('AlgEquiv', '', '5.1e-2', '51/1000', 1, '', ''),
        array('AlgEquiv', '', '0.333333333333333', '1/3', 0, '', ''),
        array('AlgEquiv', '', '(0.5+x)*2', '2*x+1', 1, '', ''),

        array('AlgEquiv', '', 'sqrt(-1)', '%i', 1, '', 'Complex numbers'),
        array('AlgEquiv', '', '%i', 'e^(i*pi/2)', 1, '', ''),
        array('AlgEquiv', '', '(4*sqrt(3)*%i+4)^(1/5)', '8^(1/5)*(cos(%pi/15)+%i*sin(%pi/15))', 1, '', ''),
        array('AlgEquiv', '', '(4*sqrt(3)*%i+4)^(1/5)', 'rectform((4*sqrt(3)*%i+4)^(1/5))', 1, '', ''),
        array('AlgEquiv', '', '(4*sqrt(3)*%i+4)^(1/5)', 'polarform((4*sqrt(3)*%i+4)^(1/5))', 1, '', ''),
        array('AlgEquiv', '', '%i/sqrt(x)', 'sqrt(-1/x)', 1, '', ''),

        array('AlgEquiv', '', 'inf', 'inf', 1, '', 'Infinity'),
        array('AlgEquiv', '', 'inf', '-inf', 0, '', ''),
        array('AlgEquiv', '', '2*inf', 'inf', 0, '', ''),
        array('AlgEquiv', '', '0*inf', '0', 1, '', ''),

        array('AlgEquiv', '', 'x^(1/2)', 'sqrt(x)', 1, '', 'Powers and roots'),
        array('AlgEquiv', '', 'x', 'sqrt(x^2)', 0, '', ''),
        array('AlgEquiv', '', 'abs(x)', 'sqrt(x^2)', 1, '', ''),
        array('AlgEquiv', '', 'sqrt((x-3)*(x-5))', 'sqrt(x-3)*sqrt(x-5)', 0, '', ''),
        array('AlgEquiv', '', '1/sqrt(x)', 'sqrt(1/x)', 1, '', ''),
        array('AlgEquiv', '', 'x-1', '(x^2-1)/(x+1)', 1, '', ''),
        array('AlgEquiv', '', '2^((1/5.1)*t)', '2^((1/5.1)*t)', 1, '', ''),
        array('AlgEquiv', '', '2^((1/5.1)*t)', '2^(0.196078431373*t)', 0, '', ''),
        array('AlgEquiv', '', 'a^b*a^c', 'a^(b+c)', 1, '', ''),
        array('AlgEquiv', '', '(4*sqrt(3)*%i+4)^(1/5)', '6^(1/5)*cos(%pi/15)-6^(1/5)*%i*sin(%pi/15)', 0, '', ''),
        array('AlgEquiv', '', '2+2*sqrt(3+x)', '2+sqrt(12+4*x)', 1, '', ''),
        array('AlgEquiv', '', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 1, '',
            'Expressions with subscripts'),
        array('AlgEquiv', '', 'rho*z*V/(4*pi*epsilon[1]*(R^2+z^2)^(3/2))', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 0, '', ''),

        array('AlgEquiv', '', '(x-1)^2', 'x^2-2*x+1', 1, '', 'Polynomials and rational function'),
        array('AlgEquiv', '', '(x-1)*(x^2+x+1)', 'x^3-1', 1, '', ''),
        array('AlgEquiv', '', '(x-1)^(-2)', '1/(x^2-2*x+1)', 1, '', ''),
        array('AlgEquiv', '', '1/(4*x-(%pi+sqrt(2)))', '1/(x+1)', 0, '', ''),
        array('AlgEquiv', '', '(x-a)^6000', '(x-a)^6000', 1, '', ''),
        array('AlgEquiv', '', '(a-x)^6000', '(x-a)^6000', 1, '', ''),
        array('AlgEquiv', '', '(x-a)^6000', '(x-a)^5999', 0, '', ''),
        array('AlgEquiv', '', '(k+8)/(k^2+4*k-12)', '(k+8)/(k^2+4*k-12)', 1, '', ''),
        array('AlgEquiv', '', '(k+7)/(k^2+4*k-12)', '(k+8)/(k^2+4*k-12)', 0, '', ''),
        array('AlgEquiv', '', '-(2*k+6)/(k^2+4*k-12)', '-(2*k+6)/(k^2+4*k-12)', 1, '', ''),
        array('AlgEquiv', '', '1/n-1/(n+1)', '1/(n*(n+1))', 1, '', ''),
        array('AlgEquiv', '', '0.5*x^2+3*x-1', 'x^2/2+3*x-1', 1, '', ''),

        array('AlgEquiv', '', 'cos(x)', 'cos(-x)', 1, '', 'Trig functions'),
        array('AlgEquiv', '', 'cos(x)^2+sin(x)^2', '1', 1, '', ''),
        array('AlgEquiv', '', '2*cos(x)^2-1', 'cos(2*x)', 1, '', ''),
        array('AlgEquiv', '', 'diff(tan(10*x)^2,x)', 'cos(6*x)', 0, '', ''),
        array('AlgEquiv', '', 'exp(%i*%pi)', '-1', 1, '', ''),
        array('AlgEquiv', '', '2*cos(2*x)+x+1', '-sin(x)^2+3*cos(x)^2+x', 1, '', ''),
        array('AlgEquiv', '', '(2*sec(2*t)^2-2)/2',
            '-(sin(4*t)^2-2*sin(4*t)+cos(4*t)^2-1)*(sin(4*t)^2+2*sin(4*t)+cos(4*t)^2-1)/(sin(4*t)^2+cos(4*t)^2+2*cos(4*t)+1)^2',
            1, '', ''),
        array('AlgEquiv', '', '1+cosec(3*x)', '1+csc(3*x)', 1, '', ''),
        array('AlgEquiv', '', '-4*sec(4*z)^2*sin(6*z)-6*tan(4*z)*cos(6*z)',
            '-4*sec(4*z)^2*sin(6*z)-6*tan(4*z)*cos(6*z)', 1, '', ''),
        array('AlgEquiv', '', '-4*sec(4*z)^2*sin(6*z)-6*tan(4*z)*cos(6*z)',
            '4*sec(4*z)^2*sin(6*z)+6*tan(4*z)*cos(6*z)', 0, '', ''),
        array('AlgEquiv', '', 'log(a^2*b)', '2*log(a)+log(b)', 1, '', 'Logarithms'),
        array('AlgEquiv', '', 'lg(10^x)', 'x', 1, '', ''),
        array('AlgEquiv', '', '(2*log(2*x)+x)/(2*x)', '(log(2*x)+2)/(2*sqrt(x))', 0, '', ''),
        array('AlgEquiv', '', 'log(abs((x^2-9)))', 'log(abs(x-3))+log(abs(x+3))', 0, '', ''),
        array('AlgEquiv', '', 'e^1-e^(-1)', '2*sinh(1)', 1, '', 'Hyperbolic trig'),
        array('AlgEquiv', '', 'x', '[1,2,3]', 0, 'ATAlgEquiv_SA_not_list.', 'Lists'),
        array('AlgEquiv', '', '[1,2]', '[1,2,3]', 0, 'ATList_wronglen.', ''),
        array('AlgEquiv', '', '[1,2,4]', '[1,2,3]', 0, '(ATList_wrongentries 3).', ''),
        array('AlgEquiv', '', '[1,x>2]', '[1,2<x]', 1, '', ''),
        array('AlgEquiv', '', '[1,2,[2-x<0,{1,2,2,2, 1,3}]]', '[1,2,[2-x<0,{1,2}]]', 0,
            '(ATList_wrongentries 3: (ATList_wrongentries 2: ATSet_wrongsz)).', ''),
        array('AlgEquiv', '', '[(k+8)/(k^2+4*k-12),-(2*k+6)/(k^2+4*k-12)]', '[(k+8)/(k^2+4*k-12),-(2*k+6)/(k^2+4*k-12)]',
            1, '', ''),

        /* Note to self: Maxima's round() command uses Bankers' rounding, but significantfigures does not. */
        array('AlgEquiv', '', 'round(0.5)', '0.0', 1, '', 'Rounding of floats'),
        array('AlgEquiv', '', 'round(1.5)', '2.0', 1, '', ''),
        array('AlgEquiv', '', 'round(2.5)', '2.0', 1, '', ''),
        array('AlgEquiv', '', 'round(12.5)', '12.0', 1, '', ''),
        array('AlgEquiv', '', 'significantfigures(0.5,1)', '0.5', 1, '', ''),
        array('AlgEquiv', '', 'significantfigures(1.5,1)', '2.0', 1, '', ''),
        array('AlgEquiv', '', 'significantfigures(2.5,1)', '3.0', 1, '', ''),
        array('AlgEquiv', '', 'significantfigures(3.5,1)', '4.0', 1, '', ''),
        array('AlgEquiv', '', 'significantfigures(11.5,2)', '12.0', 1, '', ''),
        array('AlgEquiv', '', '[3,3.1,3.14,3.142,3.1416,3.14159,3.141593,3.1415927]',
            'makelist(significantfigures(%pi,i),i,8)', 1, '', ''),
        array('AlgEquiv', '', 'x', '{1,2,3}', 0, 'ATAlgEquiv_SA_not_set.', 'Sets'),
        array('AlgEquiv', '', '{1,2}', '{1,2,3}', 0, 'ATSet_wrongsz.', ''),
        array('AlgEquiv', '', '{2/4, 1/3}', '{1/2, 1/3}', 1, '', ''),
        array('AlgEquiv', '', '{A[1],A[2],A[4]}', '{A[1],A[2],A[3]}', 0, 'ATSet_wrongentries.', ''),
        array('AlgEquiv', '', '{A[1],A[2],A[3]}', '{A[1],A[2],A[3]}', 1, '', ''),
        array('AlgEquiv', '', '{1,2,4}', '{1,2,3}', 0, 'ATSet_wrongentries.', ''),
        array('AlgEquiv', '', '{1,x>4}', '{4<x, 1}', 1, '', ''),
        array('AlgEquiv', '', '{x-1=0,x>1 and 5>x}', '{x>1 and x<5,x=1}', 1, '', ''),
        array('AlgEquiv', '', '{x-1=0,x>1 and 5>x}', '{x>1 and x<5,x=2}', 0, 'ATSet_wrongentries.', ''),
        array('AlgEquiv', '', '{x-1=0,x>1 and 5>x}', '{x>1 and x<3,x=1}', 0, 'ATSet_wrongentries.', ''),
        array('AlgEquiv', '', '{-sqrt(2)/sqrt(3)}', '{-2/sqrt(6)}', -2, 'ATSet_wrongentries.',
            'Equivalence for elements of sets is different from expressions: see docs.'),
        array('AlgEquiv', '', '{[-sqrt(2)/sqrt(3),0],[2/sqrt(6),0]}', '{[2/sqrt(6),0],[-2/sqrt(6),0]}', -2,
            'ATSet_wrongentries.', ''),
        array('AlgEquiv', '', 'ev(radcan({-sqrt(2)/sqrt(3)}),simp)', 'ev(radcan({-2/sqrt(6)}),simp)', 1, '', ''),
        array('AlgEquiv', '', '{(x-a)^6000}', '{(a-x)^6000}', -2, 'ATSet_wrongentries.', ''),
        array('AlgEquiv', '', '{(k+8)/(k^2+4*k-12),-(2*k+6)/(k^2+4*k-12)}', '{(k+8)/(k^2+4*k-12),-(2*k+6)/(k^2+4*k-12)}',
            1, '', ''),

        array('AlgEquiv', '', 'matrix([1,2],[2,3])', 'matrix([1,2],[2,3])', 1, '', 'Matrices'),
        array('AlgEquiv', '', 'matrix([1,2],[2,3])', 'matrix([1,2,3],[2,3,3])', 0, 'ATMatrix_wrongsz_columns.', ''),
        array('AlgEquiv', '', 'matrix([1,2],[2,3])', 'matrix([1,2],[2,5])', 0, 'ATMatrix_wrongentries.', ''),
        array('AlgEquiv', '', 'matrix([epsilon[0],2],[2,x^2])', 'matrix([epsilon[0],2],[2,x^2])', 1, '', ''),
        array('AlgEquiv', '', 'matrix([epsilon[2],2],[2,x^2])', 'matrix([epsilon[0],2],[2,x^3])', 0, 'ATMatrix_wrongentries.', ''),
        array('AlgEquiv', '', 'matrix([x>4,{1,x^2}],[[1,2],[1,3]])', 'matrix([4-x<0,{x^2, 1}],[[1,2],[1,3]])', 1, '', ''),
        array('AlgEquiv', '', 'matrix([x>4,{1,x^2}],[[1,2],[1,3]])', 'matrix([4-x<0,{x^2, 1}],[[1,2],[1,4]])', 0,
            'ATMatrix_wrongentries.', ''),

        array('AlgEquiv', '', '1', 'x=1', 0, 'ATAlgEquiv_SA_not_equation.', 'Equations'),
        array('AlgEquiv', '', 'x=1', 'x=1', 1, 'ATEquation_sides', ''),
        array('AlgEquiv', '', '1=x', '1=x', 1, 'ATEquation_sides', ''),
        array('AlgEquiv', '', '1=x', 'x=1', 1, 'ATEquation_sides_op', ''),
        array('AlgEquiv', '', '1=1', '1=x', 0, 'ATEquation_lhs_notrhs', ''),
        array('AlgEquiv', '', '1=1', 'x=1', 0, 'ATEquation_lhs_notrhs_op', ''),
        array('AlgEquiv', '', 'x=2', 'x=1', 0, 'ATEquation_lhs_notrhs', ''),
        array('AlgEquiv', '', '2=x', 'x=1', 0, 'ATEquation_default', ''),
        array('AlgEquiv', '', 'x=x', 'y=y', 1, 'ATEquation_zero', ''),
        array('AlgEquiv', '', 'x+y=1', 'y=1-x', 1, '', ''),
        array('AlgEquiv', '', '2*x+2*y=1', 'y=0.5-x', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', '1/x+1/y=2', 'y = x/(2*x-1)', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', 'y=sin(2*x)', 'y/2=cos(x)*sin(x)', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', 'y=(x-a)^6000', 'y=(x-a)^6000', 1, 'ATEquation_sides', ''),
        array('AlgEquiv', '', 'y=(x-a)^5999', 'y=(x-a)^6000', 0, 'ATEquation_lhs_notrhs', ''),
        array('AlgEquiv', '', 'y=(a-x)^6000', 'y=(x-a)^6000', 1, 'ATEquation_sides', ''),
        array('AlgEquiv', '', 'y=(a-x)^5999', 'y=(x-a)^5999', 0, 'ATEquation_lhs_notrhs', ''),
        array('AlgEquiv', '', 'y=(a-x)^59999', 'y=(x-a)^5999', 0, 'ATEquation_lhs_notrhs', ''),
        array('AlgEquiv', '', 'x+y=i', 'y=i-x', 1, '', ''),
        array('AlgEquiv', '', '(1+%i)*(x+y)=0', 'y=-x', 1, '', ''),
        array('AlgEquiv', '', 's^2*%e^(s*t)=0', 's^2=0', 0, 'ATEquation_default', ''),
        array('AlgEquiv', '', 'x^6000-x^6001=x^5999', 'x^5999*(1-x+x^2)=0', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', 'x^6000-x^6001=x^5999', 'x^5999*(1-x+x^3)=0', 0, 'ATEquation_default', ''),
        array('AlgEquiv', '', '258552*x^7*(81*x^8+1)^398', 'x^3*(x^4+1)^399', 0, '', ''),

        array('AlgEquiv', '', 'x=y', 'x^2=y^2', 0, 'ATEquation_default',
            'Equations: Loose/gain roots with nth powers of each side.'),
        array('AlgEquiv', '', '(x-y)*(x+y)=0', 'x^2=y^2', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', 'x=1', '(x-1)^3=0', 0, 'ATEquation_default', ''),
        array('AlgEquiv', '', 'sqrt(x)=sqrt(y)', 'x=y', 0, 'ATEquation_default', ''),
        array('AlgEquiv', '', 'x=sqrt(a)', 'x^2=a', 0, 'ATEquation_default', ''),
        array('AlgEquiv', '', '(x-sqrt(a))*(x+sqrt(a))=0', 'x^2=a', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', '(x-%i*sqrt(a))*(x+%i*sqrt(a))=0', 'x^2=-a', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', '(x-%i*sqrt(abs(a)))*(x+%i*sqrt(abs(a)))=0', 'x^2=-abs(a)', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', 'y=sqrt(1-x^2)', 'x^2+y^2=1', 0, 'ATEquation_default', ''),
        array('AlgEquiv', '', '(y-sqrt(1-x^2))*(y+sqrt(1-x^2))=0', 'x^2+y^2=1', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', '(y-sqrt((1-x)*(1+x)))*(y+sqrt((1-x)*(1+x)))=0', 'x^2+y^2=1', 1, 'ATEquation_ratio', ''),
        array('AlgEquiv', '', '(x-1)*(x+1)*(y-1)*(y+1)=0', 'y^2+x^2=1+x^2*y^2', 1, 'ATEquation_ratio', ''),

        array('AlgEquiv', '', 'f(x):=1/0', 'f(x):=x^2', -1, 'CASError: Division by zero.', 'Functions'),
        array('AlgEquiv', '', '1', 'f(x):=x^2', 0, 'ATAlgEquiv_SA_not_function.', ''),
        array('AlgEquiv', '', 'f(x)=x^2', 'f(x):=x^2', 0, 'ATAlgEquiv_SA_not_function.', ''),
        array('AlgEquiv', '', 'f(x):=x^2', 'f(x,y):=x^2+y^2', 0, 'ATFunction_length_args. ATFunction_false.', ''),
        array('AlgEquiv', '', 'f(x):=x^2', 'f(x)=x^2', 0, 'ATAlgEquiv_SA_not_equation.', ''),
        array('AlgEquiv', '', 'f(x):=x^2', 'f(x):=x^2', 1, 'ATFunction_true.', ''),
        array('AlgEquiv', '', 'f(x):=x^2', 'f(x):=sin(x)', 0, 'ATFunction_false.', ''),
        array('AlgEquiv', '', 'g(x):=x^2', 'f(x):=x^2', 0, 'ATFunction_wrongname. ATFunction_true.', ''),
        array('AlgEquiv', '', 'f(y):=y^2', 'f(x):=x^2', 1, 'ATFunction_arguments_different. ATFunction_true.', ''),
        array('AlgEquiv', '', 'f(a,b):=a^2+b^2', 'f(x,y):=x^2+y^2', 1, 'ATFunction_arguments_different. ATFunction_true.', ''),
        array('AlgEquiv', '', '1', 'x>1', 0, 'ATAlgEquiv_SA_not_inequality.', 'Inequalities'),
        array('AlgEquiv', '', 'x=1', 'x>1 and x<5', 0, 'ATAlgEquiv_TA_not_equation.', ''),
        array('AlgEquiv', '', 'x<1', 'x>1', 0, 'ATInequality_backwards.', ''),
        array('AlgEquiv', '', 'x>1', 'x<=1', 0, 'ATInequality_strict. ATInequality_backwards.', ''),
        array('AlgEquiv', '', 'x>=2', 'x<2', 0, 'ATInequality_nonstrict. ATInequality_backwards.', ''),
        array('AlgEquiv', '', 'x>=1', 'x>2', 0, 'ATInequality_nonstrict.', ''),
        array('AlgEquiv', '', 'x>1', 'x>1', 1, '', ''),
        array('AlgEquiv', '', 'x>=1', 'x>=1', 1, '', ''),
        array('AlgEquiv', '', 'x>2', 'x>1', 0, '', ''),
        array('AlgEquiv', '', '1<x', 'x>1', 1, '', ''),
        array('AlgEquiv', '', '2*x>=x^2', 'x^2<=2*x', 1, '', ''),
        array('AlgEquiv', '', 'x^2+x+4<(3*x-1)*(2*x+1)', 'x^2-1>0', 1, '', ''),
        array('AlgEquiv', '', 'x>1 and x<5', 'x>1 and x<5', 1, '', ''),
        array('AlgEquiv', '', 'x>1 and x<5', '5>x and 1<x', 1, '', ''),
        array('AlgEquiv', '', 'not (x<=2 and -2<=x)', 'x>2 or -2>x', 1, '', ''),
        array('AlgEquiv', '', 'x>=1 or 1<=x', 'x>=1', 1, '', ''),
        array('AlgEquiv', '', '(x>4 and x<5) or (x<-4 and x>-5) or (x+5>0 and x<-4)',
            '(x>-5 and x<-4) or (x>4 and x<5)', 1, '', ''),
        array('AlgEquiv', '', '(x>4 and x<5) or (x<-4 and x>-5) or (x+5>0 and x<-4)',
            '(x>-5 and x<-4) or (x>8 and x<5)', 0, '', ''),
        array('AlgEquiv', '', '2*x^2+x>=6', 'x<=-2 or x>=3/2', 0, '',
            'Inequalities - not currently considered equivalent, but maybe in the future'),
        array('AlgEquiv', '', 'x^2>4', 'x>2 and x<-2', 0, '', ''),
        array('AlgEquiv', '', 'x^4>=0', 'x^2>=0', 0, '', ''),
        array('AlgEquiv', '', 'sqrt(12)', '2*sqrt(3)', 1, '', 'Surds'),
        array('AlgEquiv', '', 'sqrt(11+6*sqrt(2))', '3+sqrt(2)', 1, '', ''),
        array('AlgEquiv', '', '(19601-13860*sqrt(2))^(7/4)', '(5*sqrt(2)-7)^7', 1, '', ''),
        array('AlgEquiv', '', '(19601-13861*sqrt(2))^(7/4)', '(5*sqrt(2)-7)^7', 0, '', ''),
        array('AlgEquiv', '', '(19601-13861*sqrt(2))^(7/4)', '(5*sqrt(2)-7)^7', 0, '', ''),
        array('AlgEquiv', '', 'sqrt(2*log(26)+4-2*log(2))', 'sqrt(2*log(13)+4)', 1, '', ''),
        array('AlgEquiv', '', '(n+1)*n!', '(n+1)!', 1, '', 'Factorials'),
        array('AlgEquiv', '', 'n/n!', '1/(n-1)!', 1, '', ''),
        array('AlgEquiv', '', '3*s*diff(q(s),s)', '3*s*diff(q(s),s)', 1, '', 'Unevaluated derviatives'),
        array('AlgEquiv', '', '2/%i*ln(sqrt((1+z)/2)+%i*sqrt((1-z)/2))', '-%i*ln(z+i*sqrt(1-z^2))', -2,
            'CASError: The CAS timed out.', 'These currently fail'),
        array('AlgEquiv', '', '(-1)^n*cos(x)^n', '(-cos(x))^n', -2, '', ''),
        array('AlgEquiv', '', '-inf', 'minf', -2, 'CASError: sign: sign of und is undefined.', ''),
        array('AlgEquiv', '', '(sqrt(108)+10)^(1/3)-(sqrt(108)-10)^(1/3)', '2', -2, '', ''),
        array('AlgEquiv', '', '(sqrt(2+sqrt(2))+sqrt(2-sqrt(2)))/(2*sqrt(2))', 'sqrt(sqrt(2)+2)/2', -2, '', ''),
        array('AlgEquiv', '', '((x+3)^2*(x+3))^(1/3)', '((x+3)*(x^2+6*x+9))^(1/3)', -2, '', 'Need to factor internally.'),

        array('SubstEquiv', '', '1/0', 'x^2-2*x+1', -1, 'CASError: Division by zero.', ''),
        array('SubstEquiv', '', 'x^2+1', 'x^2+1', 1, '', ''),
        array('SubstEquiv', '', 'x^2+1', 'x^3+1', 0, '', ''),
        array('SubstEquiv', '', 'X^2+1', 'x^2+1', 1, 'ATSubstEquiv_Subst: [X = x].', ''),
        array('SubstEquiv', '', 'x^2+y', 'a^2+b', 1, 'ATSubstEquiv_Subst: [x = a,y = b].', ''),
        array('SubstEquiv', '', 'x^2+y/z', 'a^2+c/b', 1, 'ATSubstEquiv_Subst: [x = a,y = c,z = b].', ''),
        array('SubstEquiv', '', 'y=x^2', 'a^2=b', 1, 'ATSubstEquiv_Subst: [y = b,x = a].', ''),
        array('SubstEquiv', '', '{x=1,y=2}', '{x=2,y=1}', 1, 'ATSubstEquiv_Subst: [x = y,y = x].', ''),

        array('EqualComAss', '', '1/0', '0', -1, 'CASError: Division by zero. | ATEqualComAss_STACKERROR_SAns.', ''),
        array('EqualComAss', '', '0', '1/0', -1, 'CASError: Division by zero. | ATEqualComAss_STACKERROR_TAns.', ''),
        array('EqualComAss', '', '2/4', '1/2', 0, 'ATEqualComAss: (AlgEquiv:true).', 'Numbers'),
        array('EqualComAss', '', '3^2', '8', 0, 'ATEqualComAss: (AlgEquiv:false).', ''),
        array('EqualComAss', '', '3^2', '9', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '4^(1/2)', '2', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '1/3^(1/2)', '(1/3)^(1/2)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', 'sqrt(3)/3', '(1/3)^(1/2)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', 'sqrt(3)', '3^(1/2)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '2*sqrt(2)', 'sqrt(8)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '2*2^(1/2)', 'sqrt(8)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', 'sqrt(2)/4', '1/sqrt(8)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '1/sqrt(2)', '2^(1/2)/2', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', 'a^2/b^3', 'a^2*b^(-3)', 0, 'ATEqualComAss: (AlgEquiv:true).', 'Powers'),
        array('EqualComAss', '', '1+2*x', 'x*2+1', 1, '', 'Simple polynomials'),
        array('EqualComAss', '', '1+x', '2*x+1', 0, 'ATEqualComAss: (AlgEquiv:false).', ''),
        array('EqualComAss', '', '1+x+x', '2*x+1', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(x+y)+z', 'z+x+y', 1, '', ''),
        array('EqualComAss', '', 'x*x', 'x^2', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(x+5)*x', 'x*(5+x)', 1, '', ''),
        array('EqualComAss', '', 'x*(x+5)', '5*x+x^2', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(1-x)^2', '(x-1)^2', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(a-x)^6000', '(x-a)^6000', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 1, '',
            'Expressions with subscripts'),
        array('EqualComAss', '', 'rho*z*V/(4*pi*epsilon[1]*(R^2+z^2)^(3/2))', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 0,
            'ATEqualComAss: (AlgEquiv:false).', ''),
        array('EqualComAss', '', '-1+2', '2-1', 1, '', 'Unary minus'),
        array('EqualComAss', '', '-1*2+3*4', '3*4-1*2', 1, '', ''),
        array('EqualComAss', '', '(-1*2)+3*4', '10', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '-1*2+3*4', '3*4-1*2', 1, '', ''),
        array('EqualComAss', '', 'x*(-y)', '-x*y', 1, '', ''),
        array('EqualComAss', '', 'x*(-y)', '-(x*y)', 1, '', ''),
        array('EqualComAss', '', '(-x)*(-x)', 'x*x', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(-x)*(-x)', 'x^2', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '1/2', '3/6', 0, 'ATEqualComAss: (AlgEquiv:true).', 'Rational expressions'),
        array('EqualComAss', '', '1/(1+2*x)', '1/(2*x+1)', 1, '', ''),
        array('EqualComAss', '', '2/(4+2*x)', '1/(x+2)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(a*b)/c', 'a*(b/c)', 1, '', ''),
        array('EqualComAss', '', '(-x)/y', '-(x/y)', 1, '', ''),
        array('EqualComAss', '', 'x/(-y)', '-(x/y)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '-1/(1-x)', '1/(x-1)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '1/2*1/x', '1/(2*x)', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(k+8)/(k^2+4*k-12)', '(k+8)/(k^2+4*k-12)', 1, '', ''),
        array('EqualComAss', '', '(k+8)/(k^2+4*k-12)', '(k+8)/((k-2)*(k+6))', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(k+7)/(k^2+4*k-12)', '(k+8)/(k^2+4*k-12)', 0, 'ATEqualComAss: (AlgEquiv:false).', ''),
        array('EqualComAss', '', '-(2*k+6)/(k^2+4*k-12)', '-(2*k+6)/(k^2+4*k-12)', 1, '', ''),
        array('EqualComAss', '', '%i', 'e^(i*pi/2)', 0, 'ATEqualComAss: (AlgEquiv:true).', 'Complex numbers'),
        array('EqualComAss', '', '(4*sqrt(3)*%i+4)^(1/5)', 'rectform((4*sqrt(3)*%i+4)^(1/5))', 0,
            'ATEqualComAss: (AlgEquiv:false).', ''),
        array('EqualComAss', '', '(4*sqrt(3)*%i+4)^(1/5)', '8^(1/5)*(cos(%pi/15)+%i*sin(%pi/15))', 0,
            'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '(4*sqrt(3)*%i+4)^(1/5)', 'polarform((4*sqrt(3)*%i+4)^(1/5))', 0,
            'ATEqualComAss: (AlgEquiv:false).', ''),

        array('EqualComAss', '', 'y=x', 'x=y', 0, 'ATEqualComAss: (AlgEquiv:true).',
            'Equality is not included as commutative....'),
        array('EqualComAss', '', 'x+1', 'y=2*x+1', 0, 'ATEqualComAss: ATAlgEquiv_SA_not_equation.', 'Equations'),
        array('EqualComAss', '', 'y=1+2*x', 'y=2*x+1', 1, '', ''),
        array('EqualComAss', '', 'y=x+x+1', 'y=1+2*x', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '{2*x+1,2}', '{2, 1+x*2}', 1, '', 'Sets'),
        array('EqualComAss', '', '{2*x+1, 1+1}', '{2, 1+x*2}', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', '{1,2}', '{1,{2}}', 0, 'ATEqualComAss: (AlgEquiv:false)ATSet_wrongentries.', ''),
        array('EqualComAss', '', '[2*x+1,2]', '[1+x*2,2]', 1, '', 'Lists'),
        array('EqualComAss', '', '[x+x+1, 1+1]', '[1+x*2,2]', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', 'matrix([1,2],[2,3])', 'matrix([1,2],[2,3])', 1, '', 'Matrices'),
        array('EqualComAss', '', 'matrix([1,2],[2,3])', 'matrix([1,2,3],[2,3,3])', 0,
            'ATEqualComAss: (AlgEquiv:false)ATMatrix_wrongsz_columns.', ''),
        array('EqualComAss', '', 'matrix([1,2],[2,3])', 'matrix([1,2],[2,5])', 0,
            'ATEqualComAss: (AlgEquiv:false)ATMatrix_wrongentries.', ''),
        array('EqualComAss', '', 'matrix([1,2],[2,2+1])', 'matrix([1,2],[2,3])', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),
        array('EqualComAss', '', 'matrix([x+x, 1],[1, 1])', 'matrix([2*x, 1],[1, 1])', 0, 'ATEqualComAss: (AlgEquiv:true).', ''),

        array('CasEqual', '', '1/0', 'x^2-2*x+1', -1, 'CASError: Division by zero. | ATCASEqual_STACKERROR_SAns.', ''),
        array('CasEqual', '', 'x', '1/0', -1, 'CASError: Division by zero. | ATCASEqual_STACKERROR_TAns.', ''),
        array('CasEqual', '', 'x=1', '1', 0, 'ATCASEqual: ATAlgEquiv_TA_not_equation.', ''),
        array('CasEqual', '', 'a', 'A', 0, 'ATCASEqual_false.', 'Case sensitivity'),
        array('CasEqual', '', '4^(-1/2)', '1/2', 0, 'ATCASEqual: (AlgEquiv:true).', 'Numbers'),
        array('CasEqual', '', 'ev(4^(-1/2),simp)', 'ev(1/2,simp)', 1, 'ATCASEqual_true.', ''),
        array('CasEqual', '', '2^2', '4', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', '', 'a^2/b^3', 'a^2*b^(-3)', 0, 'ATCASEqual: (AlgEquiv:true).', 'Powers'),
        array('CasEqual', '', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 1,
            'ATCASEqual_true.', 'Expressions with subscripts'),
        array('CasEqual', '', 'rho*z*V/(4*pi*epsilon[1]*(R^2+z^2)^(3/2))', 'rho*z*V/(4*pi*epsilon[0]*(R^2+z^2)^(3/2))', 0,
            'ATCASEqual_false.', ''),
        array('CasEqual', '', '0.5', '1/2', 0, 'ATCASEqual: (AlgEquiv:true).', 'Mix of floats and rational numbers'),
        array('CasEqual', '', 'x^(1/2)', 'sqrt(x)', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', '', 'ev(x^(1/2),simp)', 'ev(sqrt(x),simp)', 1, 'ATCASEqual_true.', ''),
        array('CasEqual', '', 'abs(x)', 'sqrt(x^2)', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', '', 'ev(abs(x),simp)', 'ev(sqrt(x^2),simp)', 1, 'ATCASEqual_true.', ''),
        array('CasEqual', '', 'x-1', '(x^2-1)/(x+1)', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', '', 'x+x', '2*x', 0, 'ATCASEqual: (AlgEquiv:true).', 'Polynomials and rational function'),
        array('CasEqual', '', 'ev(x+x,simp)', 'ev(2*x,simp)', 1, 'ATCASEqual_true.', ''),
        array('CasEqual', '', 'x+x^2', 'x^2+x', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', '', 'ev(x+x^2,simp)', 'ev(x^2+x,simp)', 1, 'ATCASEqual_true.', ''),
        array('CasEqual', '', '(x-1)^2', 'x^2-2*x+1', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', '', '(x-1)^(-2)', '1/(x^2-2*x+1)', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', 'x', '1/n-1/(n+1)', '1/(n*(n+1))', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', '', 'cos(x)', 'cos(-x)', 0, 'ATCASEqual: (AlgEquiv:true).', 'Trig functions'),
        array('CasEqual', '', 'ev(cos(x),simp)', 'ev(cos(-x),simp)', 1, 'ATCASEqual_true.', ''),
        array('CasEqual', '', 'cos(x)^2+sin(x)^2', '1', 0, 'ATCASEqual: (AlgEquiv:true).', ''),
        array('CasEqual', '', '2*cos(x)^2-1', 'cos(2*x)', 0, 'ATCASEqual: (AlgEquiv:true).', ''),

        array('SameType', '', '1/0', '1', -1, 'CASError: Division by zero.', ''),
        array('SameType', '', '1', '1/0', -1, 'CASError: Division by zero.', ''),
        array('SameType', '', '4^(-1/2)', '1/2', 1, '', 'Numbers'),
        array('SameType', '', 'x', '[1,2,3]', 0, '', 'Lists'),
        array('SameType', '', '[1,2]', '[1,2,3]', 1, '', ''),
        array('SameType', '', '[1,x>2]', '[1,2<x]', 1, '', ''),
        array('SameType', '', '[1,x,3]', '[1,2<x,4]', 0, '', ''),
        array('SameType', '', 'x', '{1,2,3}', 0, '', 'Sets'),
        array('SameType', '', '{1,2}', '{1,2,3}', 1, '', ''),
        array('SameType', '', 'matrix([1,2],[2,3])', 'matrix([1,2],[2,3])', 1, '', 'Matrices'),
        array('SameType', '', '[[1,2],[2,3]]', 'matrix([1,2],[2,3])', 0, '', ''),
        array('SameType', '', 'matrix([1,2],[2,3])', 'matrix([1,2,3],[2,3,3])', 1, '', ''),
        array('SameType', '', 'matrix([x>4,{1,x^2}],[[1,2],[1,3]])', 'matrix([4-x<0,{x^2, 1}],[[1,2],[1,3]])', 1, '', ''),
        array('SameType', '', 'matrix([x>4,[1,x^2]],[[1,2],[1,3]])', 'matrix([4-x<0,{x^2, 1}],[[1,2],[1,4]])', 0, '', ''),
        array('SameType', '', '1', 'x=1', 0, '', 'Equations'),
        array('SameType', '', 'x=1', 'x=1', 1, '', ''),
        array('SameType', '', '1', 'x>1', 0, '', 'Inequalities'),
        array('SameType', '', 'x>2', 'x>1', 1, '', ''),
        array('SameType', '', 'x>1', 'x>=1', 1, '', ''),
        array('SameType', '', 'x>1 and x<3', 'x>=1', 1, '', ''),
        array('SameType', '', '{x>1,x<3}', 'x>=1', 0, '', ''),

        array('SysEquiv', '', '1/0', '[(x-1)*(x+1)=0]', -1, 'CASError: Division by zero. | ATSysEquiv_STACKERROR_SAns.',
            'Basic tests'),
        array('SysEquiv', '', '[(x-1)*(x+1)=0]', '1/0', -1, 'CASError: Division by zero. | ATSysEquiv_STACKERROR_TAns.', ''),
        array('SysEquiv', '', '1', '[(x-1)*(x+1)=0]', 0, 'ATSysEquiv_SA_not_list.', ''),
        array('SysEquiv', '', '[(x-1)*(x+1)=0]', '1', 0, 'ATSysEquiv_SB_not_list.', ''),
        array('SysEquiv', '', '[1]', '[90=v*t,90=(v+5)*(t-1/4)]', 0, 'ATSysEquiv_SA_not_eq_list.', ''),
        array('SysEquiv', '', '[(x-1)*(x+1)=0]', '[1]', 0, 'ATSysEquiv_SB_not_eq_list.', ''),
        array('SysEquiv', '', '[x^2]', '[(x-1)*(x+1)=0]', 0, 'ATSysEquiv_SA_not_eq_list.', ''),
        array('SysEquiv', '', '[90=v*t^t,90=(v+5)*(t-1/4)]', '[90=v*t,90=(v+5)*(t-1/4)]', 0,
            'ATSysEquiv_SA_not_poly_eq_list.', ''),
        array('SysEquiv', '', '[90=v*t,90=(v+5)*(t-1/4)]', '[90=v*t^t,90=(v+5)*(t-1/4)]', 0,
            'ATSysEquiv_SB_not_poly_eq_list.', ''),
        array('SysEquiv', '', '[x^2=1]', '[(x-1)*(x+1)=0]', 1, '', 'Tests of equivalence'),
        array('SysEquiv', '', '[x=1]', '[(x-1)*(x+1)=0,(x-1)*(x-3)=0]', 1, 'ATSysEquiv_SA_Completely_solved.', ''),
        array('SysEquiv', '', '[x^2=1]', '[(x-1)*(x+1)*(x-2)=0]', 0, 'ATSysEquiv_SA_system_overdetermined.', ''),
        array('SysEquiv', '', '[x=1,y=-1]', '[(x-1)*(y+1)=0]', 0, 'ATSysEquiv_SA_Not_completely_solved.', ''),
        array('SysEquiv', '', '[x=1]', '[(x-1)*(x+1)=0]', 0, 'ATSysEquiv_SA_Not_completely_solved.', ''),
        array('SysEquiv', '', '[x=1]', '[(x-1)*(x+1)*y=0]', 0, 'ATSysEquiv_SA_Not_completely_solved.', ''),
        array('SysEquiv', '', '[90=v*t,90=(v+5)*(t-1/4)]', '[90=v*t,90=(v+5)*(t-1/4)]', 1, '', ''),
        array('SysEquiv', '', '[d=90,d=v*t,d=(v+5)*(t-1/4)]', '[90=v*t,90=(v+5)*(t-1/4)]', 1, '', ''),
        array('SysEquiv', '', '[90=v*t,90=(v+5)*(t*x-1/4)]', '[90=v*t,90=(v+5)*(t-1/4)]', 0, 'ATSysEquiv_SA_extra_variables.', ''),
        array('SysEquiv', '', '[90=v*t,90=(v+5)*(t-1/4)]', '[90=v*t,90=(v+5)*(t*x-1/4)]', 0,
            'ATSysEquiv_SA_missing_variables.', ''),
        array('SysEquiv', '', '[90=v*t]', '[90=v*t,90=(v+5)*(t-1/4)]', 0, 'ATSysEquiv_SA_system_underdetermined.', ''),
        array('SysEquiv', '', '[90=v*t,90=(v+5)*(t-1/4),90=(v+6)*(t-1/5)]', '[90=v*t,90=(v+5)*(t-1/4)]', 0,
            'ATSysEquiv_SA_system_overdetermined.', ''),
        array('SysEquiv', '', '[90=v*t,90=(v+5)*(t-1/4),90=(v+6)*(t-1/5),90=(v+7)*(t-1/4),90=(v+8)*(t-1/3)]',
            '[90=v*t,90=(v+5)*(t-1/4)]', 0, 'ATSysEquiv_SA_system_overdetermined.', ''),

        array('Expanded', '', '1/0', '0', -1, 'CASError: Division by zero.', ''),
        array('Expanded', '', 'x>2', 'x^2-2*x+1', 0, 'ATExpanded_SA_not_expression.', ''),
        array('Expanded', '', 'x^2-1', '0', 1, 'ATExpanded_TRUE.', ''),
        array('Expanded', '', '2*(x-1)', '0', 0, 'ATExpanded_FALSE.', ''),
        array('Expanded', '', '(x-1)*(x+1)', '0', 0, 'ATExpanded_FALSE.', ''),
        array('Expanded', '', '(x-a)*(x-b)', '0', 0, 'ATExpanded_FALSE.', ''),
        array('Expanded', '', 'x^2-(a+b)*x+a*b', '0', 0, 'ATExpanded_FALSE.', ''),
        array('Expanded', '', 'x^2-a*x-b*x+a*b', '0', 1, 'ATExpanded_TRUE.', ''),
        array('Expanded', '', 'cos(2*x)', '0', 1, 'ATExpanded_TRUE.', ''),
        array('Expanded', '', 'p+1', '0', 1, 'ATExpanded_TRUE.', ''),
        array('Expanded', '', '(p+1)*(p-1)', '0', 0, 'ATExpanded_FALSE.', ''),
        array('Expanded', '', '(a-x)^6000', '0', -2, 'ATExpanded_TRUE.',
            'This fails, but you are never going to ask students to do this anyway...'),

        array('FacForm', 'x', '1/0', '0', -1, 'CASError: Division by zero. | ATFacForm_STACKERROR_SAns.', ''),
        array('FacForm', 'x', '0', '1/0', -1, 'CASError: Division by zero. | ATFacForm_STACKERROR_TAns.', ''),
        array('FacForm', '1/0', '0', '0', -1, 'CASError: Division by zero. | ATFacForm_STACKERROR_TAns.', ''),
        array('FacForm', 'x', '2', '2', 1, 'ATFacForm_int_true.', 'Trivial cases'),
        array('FacForm', 'x', '1/3', '1/3', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '3*x^2', '3*x^2', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '4*x^2', '4*x^2', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '2*(x-1)', '2*x-2', 1, 'ATFacForm_true.', 'Linear integer factors'),
        array('FacForm', 'x', '2*x-2', '2*x-2', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '2*(x+1)', '2*x-2', 0, 'ATFacForm_isfactored. ATFacForm_default_true. ATFacForm_notalgequiv.', ''),
        array('FacForm', 'x', '2*x+2', '2*x-2', 0, 'ATFacForm_notfactored. ATFacForm_notalgequiv.', ''),
        array('FacForm', 'x', '2*(x+0.5)', '2*x+1', 1, 'ATFacForm_default_true.', ''),
        array('FacForm', 'x', 't*(2*x+1)', 't*(2*x+1)', 1, 'ATFacForm_true.', 'Linear factors'),
        array('FacForm', 'x', 't*x+t', 't*(x+1)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '2*x*(x-3)', '2*x^2-6*x', 1, 'ATFacForm_true.', 'Quadratic, with no const'),
        array('FacForm', 'x', '2*(x^2-3*x)', '2*x*(x-3)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', 'x*(2*x-6)', '2*x*(x-3)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '(x+2)*(x+3)', '(x+2)*(x+3)', 1, 'ATFacForm_true.', 'Quadratic'),
        array('FacForm', 'x', '(x+2)*(2*x+6)', '2*(x+2)*(x+3)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '(z*x+z)*(2*x+6)', '2*z*(x+1)*(x+3)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '(x+t)*(x-t)', 'x^2-t^2', 1, 'ATFacForm_true.', ''),
        array('FacForm', 't', 't^2-1', '(t-1)*(t+1)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '(2-x)*(3-x)', '(x-2)*(x-3)', 1, 'ATFacForm_true.', 'These are delicate cases!'),
        array('FacForm', 'x', '(1-x)^2', '(x-1)^2', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '-(1-x)^2', '-(x-1)^2', 1, 'ATFacForm_default_true.', ''),
        array('FacForm', 'x', '4*(1-x/2)^2', '(x-2)^2', 1, 'ATFacForm_default_true.', ''),
        array('FacForm', 'x', '(x-1)*(x^2+x+1)', 'x^3-1', 1, 'ATFacForm_true.', 'Cubics'),
        array('FacForm', 'x', 'x^3-x+1', 'x^3-x+1', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '7*x^3-7*x+7', '7*(x^3-x+1)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '(1-x)*(2-x)*(3-x)', '-x^3+6*x^2-11*x+6', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '(2-x)*(2-x)*(3-x)', '-x^3+7*x^2-16*x+12', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '(2-x)^2*(3-x)', '-x^3+7*x^2-16*x+12', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '(x^2-4*x+4)*(3-x)', '-x^3+7*x^2-16*x+12', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '(x^2-3*x+2)*(3-x)', '-x^3+6*x^2-11*x+6', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'y', '3*y^3-6*y^2-24*y', '3*(y-4)*y*(y+2)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'y', '3*(y^3-2*y^2-8*y)', '3*(y-4)*y*(y+2)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'y', '3*y*(y^2-2*y-8)', '3*(y-4)*y*(y+2)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'y', '3*(y^2-4*y)*(y+2)', '3*(y-4)*y*(y+2)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'y', '(y-4)*y*(3*y+6)', '3*(y-4)*y*(y+2)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '(a-x)^6000', '(a-x)^6000', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '(x-a)^6000', '(a-x)^6000', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'sin(x)', '(sin(x)+1)*(sin(x)-1)', 'sin(x)^2-1', 1, 'ATFacForm_true.', 'Not polynomials in a variable'),
        array('FacForm', 'cos(t)', '(cos(t)-sqrt(2))^2', 'cos(t)^2-2*sqrt(2)*cos(t)+2', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '7', '7', 1, 'ATFacForm_int_true.', ''),
        array('FacForm', 'x', '24*(x-1/4)', '24*x-6', 1, 'ATFacForm_default_true.', 'Factors over other fields'),
        array('FacForm', 'x', '(x-sqrt(2))*(x+sqrt(2))', 'x^2-2', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '(%i*x-2*%i)', '%i*(x-2)', 0, 'ATFacForm_notfactored.', ''),
        array('FacForm', 'x', '%i*(x-2)', '(%i*x-2*%i)', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '(x-%i)*(x+%i)', 'x^2+1', 1, 'ATFacForm_true.', ''),
        array('FacForm', 'x', '(x-1)*(x+(1+sqrt(3)*%i)/2)*(x+(1-sqrt(3)*%i)/2)', 'x^3-1', 1, 'ATFacForm_default_true.', ''),

        array('CompSquare', '', '1/0', '0', -1, 'STACKERROR_OPTION.', ''),
        array('CompSquare', 'x', '1/0', '0', -1, 'ATCompSquare_STACKERROR_SAns.', ''),
        array('CompSquare', 'x', '0', '1/0', -1, 'ATCompSquare_STACKERROR_TAns.', ''),
        array('CompSquare', '1/0', '0', '0', -1, 'ATCompSquare_STACKERROR_TAns.', ''),
        array('CompSquare', 'x', '1', '(x-1)^2+1', 0, 'ATCompSquare_SA_not_depend_var.', 'Category errors.'),
        array('CompSquare', 'x', '(t-1)^2+1', '(x-1)^2+1', 0, 'ATCompSquare_SA_not_depend_var.', ''),
        array('CompSquare', 'x', '(x-1)^2+1=0', '(x-1)^2+1', 0, 'ATCompSquare_STACKERROR_LIST.', ''),
        array('CompSquare', 'x', 'sin(x-1)+a-1', '(x-1)^2+1', 0, 'ATCompSquare_false_not_AlgEquiv.', ''),
        array('CompSquare', 'x', '1', '1', 1, 'ATCompSquare_true_trivial.', 'Trivial cases'),
        array('CompSquare', 'x', 'x-a', 'x-a', 1, 'ATCompSquare_true_trivial.', ''),
        array('CompSquare', 'x', 'x^2', 'x^2', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'x', 'x^2-1', '(x-1)*(x+1)', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'x', '(x-1)^2*k', '(x-1)^2*k', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'x', '(x-1)^2/k', '(x-1)^2/k', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'x', '(x-1)^2+1', '(x-1)^2+1', 1, 'ATCompSquare_true.', 'Normal cases'),
        array('CompSquare', 'x', '(X-1)^2+1', '(x-1)^2+1', 0, 'ATCompSquare_SA_not_depend_var.', ''),
        array('CompSquare', 'x', '9*(x-1)^2+1', '(3*x-3)^2+1', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'x', '(x-1)^2+1', '(x+1)^2+1', 0, 'ATCompSquare_true_not_AlgEquiv.', ''),
        array('CompSquare', 'x', '(x-a^2)^2+1+b', '(x-a^2)^2+1+b', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'x', 'x^2-2*x+2', '(x-1)^2+1', 0, 'ATCompSquare_false_no_summands.', ''),
        array('CompSquare', 'x', 'x+1', '(x-1)^2+1', 0, 'ATCompSquare_false_not_AlgEquiv.', ''),
        array('CompSquare', 'x', 'a*(x-1)^2+1', 'a*(x-1)^2+1', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'sin(x)', '(sin(x)-1)^2+1', '(sin(x)-1)^2+1', 1, 'ATCompSquare_true.', 'Not simple variable'),
        array('CompSquare', 'x^2', '(x^2-1)^2+1', '(x^2-1)^2+1', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'y', '(y-1)^2+1', '(y-1)^2+1', 1, 'ATCompSquare_true.', ''),
        array('CompSquare', 'y', '(y+1)^2+1', '(y-1)^2+1', 0, 'ATCompSquare_true_not_AlgEquiv.', ''),
        array('CompSquare', 'sin(x)', '(x-1)^2+1', '(sin(x)-1)^2+1', 0, 'ATCompSquare_SA_not_depend_var.', ''),

        array('SingleFrac', '', '1/0', '1/n', -1, 'CASError: Division by zero. | ATSingleFrac_STACKERROR_SAns.', ''),
        array('SingleFrac', '', '0', '1/0', -1, 'CASError: Division by zero. | ATSingleFrac_STACKERROR_TAns.', ''),
        array('SingleFrac', '', 'x=3', '2', 0, 'ATSingleFrac_SA_not_expression.', ''),
        array('SingleFrac', '', '3', '3', 1, '', ''),
        array('SingleFrac', '', '3', '2', 0, 'ATSingleFrac_ret_exp.', ''),
        array('SingleFrac', '', '1/m', '1/n', 0, 'ATSingleFrac_true. ATSingleFrac_ret_exp.', ''),
        array('SingleFrac', '', '1/n', '1/n', 1, 'ATSingleFrac_true.', ''),
        array('SingleFrac', '', 'a+1/2', '(2*a+1)/2', 0, 'ATSingleFrac_part.', ''),
        array('SingleFrac', '', 'a+1/2', '(2*a+1)/2', 0, 'ATSingleFrac_part.', ''),
        array('SingleFrac', '', '4/(x^2+2*x-24)+2/(x^2+4*x-12)', '(6*x-16)/(x^3-28*x+48)', 0, 'ATSingleFrac_part.', ''),
        array('SingleFrac', '', '2*(1/n)', '2/n', 0, 'ATSingleFrac_part.', '2 subtly different answers for the same question'),
        array('SingleFrac', '', '2/n', '2/n', 1, 'ATSingleFrac_true.', ''),
        array('SingleFrac', '', '2/(n+1)', '1/(n+1)', 0, 'ATSingleFrac_true. ATSingleFrac_ret_exp.', 'Simple Mistakes'),
        array('SingleFrac', '', '(2*n+1)/(n+2)', '1/n', 0, 'ATSingleFrac_true. ATSingleFrac_ret_exp.', ''),
        array('SingleFrac', '', '(2*n)/(n*(n+2))', '(2*n)/(n*(n+3))', 0, 'ATSingleFrac_true. ATSingleFrac_ret_exp.', ''),
        array('SingleFrac', '', '(x-1)/(x^2-1)', '1/(x+1)', 1, 'ATSingleFrac_true.', ''),
        array('SingleFrac', '', '(1/2)/(3/4)', '2/3', 0, 'ATSingleFrac_div.', 'Fractions within fractions'),
        array('SingleFrac', '', '(x-2)/4/(2/x^2)', '(x-2)*x^2/8', 0, 'ATSingleFrac_div.', ''),
        array('SingleFrac', '', '1/(1-1/x)', 'x/(x-1)', 0, 'ATSingleFrac_div.', ''),

        array('PartFrac', '', '1/0', '3*x^2', -1, 'STACKERROR_OPTION.', ''),
        array('PartFrac', 'x', '1/0', '3*x^2', -1, 'ATPartFrac_STACKERROR_SAns.', ''),
        array('PartFrac', '1/0', '0', '0', -1, 'ATPartFrac_STACKERROR_TAns.', ''),
        array('PartFrac', 'x', '0', '1/0', -1, 'ATPartFrac_STACKERROR_TAns.', ''),
        array('PartFrac', 'n', '1/n=0', '1/n', 0, 'ATPartFrac_SA_not_expression.', ''),
        array('PartFrac', 'n', '1/n', '{1/n}', 0, 'ATPartFrac_TA_not_expression.', ''),
        array('PartFrac', 'n', '1/m', '1/n', 0, 'ATPartFrac_diff_variables.', 'Basic tests'),
        array('PartFrac', 'n', '1/n', '1/n', 1, 'ATPartFrac_true.', ''),
        array('PartFrac', 'n', '1/(n+1)-1/n', '1/(n+1)-1/n', 1, 'ATPartFrac_true.',
            'A simple cases, linear factors in denominator'),
        array('PartFrac', 'n', '1/(n+1)+1/(1-n)', '1/(n+1)-1/(n-1)', 1, 'ATPartFrac_true.', ''),
        array('PartFrac', 'n', '1/(2*(n-1))-1/(2*(n+1))', '1/((n-1)*(n+1))', 1, 'ATPartFrac_true.', ''),
        array('PartFrac', 'n', '1/(2*(n+1))-1/(2*(n-1))', '1/((n-1)*(n+1))', 0, 'ATPartFrac_ret_expression.', ''),
        array('PartFrac', 'x', '1/(x-1)-(x+1)/(x^2+1)', '2/((x-1)*(x^2+1))', 1, 'ATPartFrac_true.',
            'Irreducible quadratic in denominator'),
        array('PartFrac', 'x', '1/(2*x-2)-(x+1)/(2*(x^2+1))', '1/((x-1)*(x^2+1))', 1, 'ATPartFrac_true.', ''),
        array('PartFrac', 'x', '1/(2*(x-1))+x/(2*(x^2+1))', '1/((x-1)*(x^2+1))', 0, 'ATPartFrac_ret_expression.', ''),
        array('PartFrac', 'x', '3/(x+1) + 3/(x+2)', '3*(2*x+3)/((x+1)*(x+2))', 1, 'ATPartFrac_true.',
            '2 answers to the same question'),
        array('PartFrac', 'x', '3*(1/(x+1) + 1/(x+2))', '3*(2*x+3)/((x+1)*(x+2))', 1, 'ATPartFrac_true.', ''),
        array('PartFrac', 'x', '3*x*(1/(x+1) + 2/(x+2))', '-12/(x+2)-3/(x+1)+9', 0, 'ATPartFrac_false_degree.',
            'Algebraically equivalent, but numerators of same order than denominator, ie not in partial fraction form.'),
        array('PartFrac', 'x', '(3*x+3)*(1/(x+1) + 2/(x+2))', '9-6/(x+2)', 0, 'ATPartFrac_false_degree.', ''),
        array('PartFrac', 'n', 'n/(2*n-1)-(n+1)/(2*n+1)', '1/(4*n-2)-1/(4*n+2)', 0, 'ATPartFrac_false_degree.', ''),
        array('PartFrac', 'x', '10/(x+3) - 2/(x+2) + x -2', '(x^3 + 3*x^2 + 4*x +2)/((x+2)*(x+3))', 1, 'ATPartFrac_true.',
            'Correct Answer, Numerator > Denominator'),
        array('PartFrac', 'x', '2*x+1/(x+1)+1/(x-1)', '2*x^3/(x^2-1)', 1, 'ATPartFrac_true.', ''),
        array('PartFrac', 'n', '1/(n*(n-1))', '1/(n*(n-1))', 0, 'ATPartFrac_false_factor.', 'Simple mistakes'),
        array('PartFrac', 'n', '1/(n-1)-1/n^2', '1/((n+1)*n)', 0, 'ATPartFrac_denom_ret.', ''),
        array('PartFrac', 'n', '1/(n-1)-1/n', '1/(n-1)+1/n', 0, 'ATPartFrac_ret_expression.', ''),
        array('PartFrac', 'x', '1/(x+1)-1/x', '1/(x-1)+1/x', 0, 'ATPartFrac_ret_expression.', ''),
        array('PartFrac', 'n', '1/(n*(n+1))+1/n', '2/n-1/(n+1)', 0, 'ATPartFrac_false_factor.', ''),
        array('PartFrac', 's', '2/(x+1)-1/(x+2)', 's/((s+1)*(s+2))', 0, 'ATPartFrac_diff_variables.',
            'Different Variables'),
        array('PartFrac', 's', 's/((s+1)^2) + s/(s+2) - 1/(s+1)', 's/((s+1)*(s+2))', 0,
            'ATPartFrac_denom_ret.', 'Too many parts in the partial fraction'),
        array('PartFrac', 's', 's/(s+2) - 1/(s+1)', 's/((s+1)*(s+2)*(s+3))', 0,
            'ATPartFrac_denom_ret.', 'Too few parts in the partial fraction'),
        array('PartFrac', 'x', '1/(x+1) + 1/(x+2)', '2/(x+1) + 1/(x+2)', 0,
            'ATPartFrac_ret_expression.', 'Addition and Subtraction errors'),
        array('PartFrac', 'x', '1/(x+1) + 1/(x+2)', '1/(x+1) + 2/(x+2)', 0,
            'ATPartFrac_ret_expression.', ''),
        array('PartFrac', 'x', '1/(x+1) + 1/(x+2)', '1/(x+3) + 1/(x+2)', 0,
            'ATPartFrac_ret_expression.', 'Denominator Error'),
        array('PartFrac', 'x', '(2*x+1)/(x^2+1)-2/(x-1)', '(2*x+1)/(x^2+1)-2/(x-1)', 1, 'ATPartFrac_true.', ''),
        array('PartFrac', 'x', '(-5/(x+3))+(16/(x+3)^2)-(2/(x+2))+4', '(-5/(x+3))+(16/(x+3)^2)-(2/(x+2))+4', 1,
            'ATPartFrac_true.', ''),
        array('PartFrac', 'x', '(3*x^2-5)/((x-4)^2*x)', '(3*x^2-5)/((x-4)^2*x)', 0,
            'ATPartFrac_false_factor.', 'Cubic in the denominator'),
        array('PartFrac', 'x', '-4/(16*x)+53/(16*(x-4))+43/(4*(x-4)^2)', '(3*x^2-5)/((x-4)^2*x)', 0,
            'ATPartFrac_ret_expression.', ''),
        array('PartFrac', 'x', '-5/(16*x)+53/(16*(x-4))+43/(4*(x-4)^2)', '(3*x^2-5)/((x-4)^2*x)', 1,
            'ATPartFrac_true.', ''),
        array('PartFrac', 'x', '(5*x+6)/((x+1)*(x+5)^2)', '(5*x+6)/((x+1)*(x+5)^2)', 0,
            'ATPartFrac_false_factor.', ''),
        array('PartFrac', 'x', '-1/(16*(x+5))+19/(4*(x+5)^2)+1/(16*(x+1))', '(5*x+6)/((x+1)*(x+5)^2)', 1,
            'ATPartFrac_true.', ''),
        array('PartFrac', 'x', '5/(x*(x+3)*(5*x-2))', '5/(x*(x+3)*(5*x-2))', 0, 'ATPartFrac_false_factor.', ''),
        array('PartFrac', 'x', '125/(34*(5*x-2))+5/(51*(x+3))-5/(6*x)', '5/(x*(x+3)*(5*x-2))', 1, 'ATPartFrac_true.', ''),
        array('PartFrac', 'x', '(3*x^2-5)/((4*x-4)^2*x)', '(3*x^2-5)/((4*x-4)^2*x)', 0, 'ATPartFrac_false_factor.', ''),
        array('PartFrac', 'x', '-4/(16*x)+1/(2*(x-1))-1/(8*(x-1)^2)', '(3*x^2-5)/((4*x-4)^2*x)', 0,
            'ATPartFrac_ret_expression.', ''),
        array('PartFrac', 'x', '-5/(16*x)+1/(2*(x-1))-1/(8*(x-1)^2)', '(3*x^2-5)/((4*x-4)^2*x)', 1, 'ATPartFrac_true.', ''),

        array('Diff', '', '1/0', '3*x^2', -1, 'STACKERROR_OPTION.', ''),
        array('Diff', '(x', '0', '1/0', -1, 'STACKERROR_OPTION.', ''),
        array('Diff', 'x', '1/0', '3*x^2', -1, 'CASError: Division by zero. | ATDiff_STACKERROR_SAns.', ''),
        array('Diff', 'x', '0', '1/0', -1, 'CASError: Division by zero. | ATDiff_STACKERROR_TAns.', ''),
        array('Diff', '1/0', '0', '0', -1, 'CASError: Division by zero. | ATDiff_STACKERROR_TAns.', ''),
        array('Diff', 'x', '3*x^2', '3*x^2', 1, 'ATDiff_true.', 'Basic tests'),
        array('Diff', 'x', '3*X^2', '3*x^2', 0, 'ATDiff_var_SB_notSA.', ''),
        array('Diff', 'x', 'x^4/4', '3*x^2', 0, 'ATDiff_int.', ''),
        array('Diff', 'x', 'x^4/4+1', '3*x^2', 0, 'ATDiff_int.', ''),
        array('Diff', 'x', 'x^4/4+c', '3*x^2', 0, 'ATDiff_int.', ''),
        array('Diff', 'x', 'y=x^4/4', 'x^4/4', 0, 'ATDiff_SA_not_expression.', ''),
        array('Diff', 'x', 'x^4/4', 'y=x^4/4', 0, '', ''),
        array('Diff', 'x', 'y=x^4/4', 'y=x^4/4', 0, 'ATDiff_SA_not_expression.', ''),
        array('Diff', 'x', '6000*(x-a)^5999', '6000*(x-a)^5999', 1, 'ATDiff_true.', ''),
        array('Diff', 'x', '5999*(x-a)^5999', '6000*(x-a)^5999', 0, '', ''),
        array('Diff', 'x', 'y^2-2*y+1', 'x^2-2*x+1', 0, 'ATDiff_var_SB_notSA.', 'Variable mismatch tests'),
        array('Diff', 'x', 'x^2-2*x+1', 'y^2-2*y+1', 0, 'ATDiff_var_SA_notSB.', ''),
        array('Diff', 'z', 'y^2+2*y+1', 'x^2-2*x+1', 0, 'ATDiff_var_notSASB_SAnceSB.', ''),
        array('Diff', 'y', 'x^4/4', '3*x^2', 0, '', ''),

        array('Int', '', '1/0', '1', -1, 'STACKERROR_OPTION.', ''),
        array('Int', 'x', '1/0', '1', -1, 'CASError: Division by zero. | ATInt_STACKERROR_SAns.', ''),
        array('Int', 'x', '1', '1/0', -1, 'CASError: Division by zero. | ATInt_STACKERROR_TAns.', ''),
        array('Int', '1/0', '0', '0', -1, 'CASError: Division by zero. | ATInt_STACKERROR_TAns.', ''),
        array('Int', '[x,1/0]', '0', '0', -1, 'CASError: Division by zero. | ATInt_STACKERROR_TAns.', ''),
        array('Int', '[x,NOCONST,1/0]', '0', '0', -1, 'CASError: Division by zero. | ATInt_STACKERROR_TAns.', ''),
        array('Int', 'x', 'x^3/3', 'x^3/3', 0, 'ATInt_const.', 'Basic tests'),
        array('Int', 'x', 'x^3/3+1', 'x^3/3', 0, 'ATInt_const_int.', ''),
        array('Int', 'x', 'x^3/3+c', 'x^3/3', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'x^3/3+c+1', 'x^3/3', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'x^3/3+3*c', 'x^3/3', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'x^3/3-c', 'x^3/3', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'x^3/3+c+k', 'x^3/3', 0, 'ATInt_weirdconst.', ''),
        array('Int', 'x', 'x^3/3+c^2', 'x^3/3', 0, 'ATInt_weirdconst.', ''),
        array('Int', 'x', 'x^3/3*c', 'x^3/3', 0, 'ATInt_generic.', ''),
        array('Int', 'x', 'X^3/3+c', 'x^3/3', 0, 'ATInt_generic. ATInt_var_SB_notSA.', ''),
        array('Int', 'x', 'sin(2*x)', 'x^3/3', 0, 'ATInt_generic.', ''),
        array('Int', 'x', 'x^2/2-2*x+2+c', '(x-2)^2/2', 1, 'ATInt_true.', ''),
        array('Int', 't', '(t-1)^5/5+c', '(t-1)^5/5', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'cos(2*x)/2+1+c', 'cos(2*x)/2', 1, 'ATInt_true.', ''),
        array('Int', 'x', '(x-a)^6001/6001+c', '(x-a)^6001/6001', 1, 'ATInt_true.', ''),
        array('Int', 'x', '(x-a)^6001/6001', '(x-a)^6001/6001', 0, 'ATInt_const.', ''),
        array('Int', 'x', '6000*(x-a)^5999', '(x-a)^6001/6001', 0, 'ATInt_diff.', ''),
        array('Int', 'x', '4*%e^(4*x)/(%e^(4*x)+1)', 'log(%e^(4*x)+1)+c', 0, 'ATInt_generic.', ''),
        array('Int', 'x', 'x^3/3+c', 'x^3/3+c', 1, 'ATInt_true.', 'The teacher adds a constant'),
        array('Int', 'x', 'x^2/2-2*x+2+c', '(x-2)^2/2+k', 1, 'ATInt_true.', ''),
        array('Int', '[x,NOCONST]', 'x^3/3', 'x^3/3', 1, 'ATInt_const_condone.',
            'The teacher condones lack of constant, or numerical constant'),
        array('Int', '[x,NOCONST]', 'x^3/3+c', 'x^3/3', 1, 'ATInt_true.', ''),
        array('Int', '[x,NOCONST]', 'x^2/2-2*x+2', '(x-2)^2/2+k', 1, 'ATInt_const_condone.', ''),
        array('Int', '[x,NOCONST]', 'x^3/3+1', 'x^3/3', 1, 'ATInt_const_int_condone.', ''),
        array('Int', '[x,NOCONST]', 'x^3/3+c^2', 'x^3/3', 0, 'ATInt_weirdconst.', ''),
        array('Int', 'x', 'exp(x)+c', 'exp(x)', 1, 'ATInt_true.', 'Special case'),
        array('Int', 'x', 'exp(x)', 'exp(x)', 0, 'ATInt_const.', ''),
        array('Int', '[x,NOCONST]', 'exp(x)', 'exp(x)', 1, 'ATInt_const_condone.', ''),
        array('Int', 'x', '2*x', 'x^3/3', 0, 'ATInt_diff.', 'Student differentiates by mistake'),
        array('Int', 'x', '2*x+c', 'x^3/3', 0, 'ATInt_diff.', ''),
        array('Int', 'x', 'ln(x)', 'ln(x)', 0, 'ATInt_const.', 'Sloppy logs (teacher ignores abs(x) )'),
        array('Int', '[x,NOCONST]', 'ln(x)', 'ln(x)', 1, 'ATInt_const_condone.', ''),
        array('Int', 'x', 'ln(x)+c', 'ln(x)+c', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'ln(k*x)', 'ln(x)+c', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'ln(x)', 'ln(abs(x))+c', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', 'Fussy logs (teacher uses abs(x) )'),
        array('Int', 'x', 'ln(x)+c', 'ln(abs(x))+c', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', '[x, NOCONST]', 'ln(x)', 'ln(abs(x))+c', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', 'x', 'ln(abs(x))', 'ln(abs(x))+c', 0, 'ATInt_const.', ''),
        array('Int', 'x', 'ln(abs(x))+c', 'ln(abs(x))+c', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'ln(k*x)', 'ln(abs(x))+c', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', 'x', 'ln(k*abs(x))', 'ln(abs(x))+c', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'ln(abs(k*x))', 'ln(abs(x))+c', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'ln(x)', 'ln(k*abs(x))', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', 'Teacher uses ln(k*abs(x))'),
        array('Int', 'x', 'ln(x)+c', 'ln(k*abs(x))', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', 'x', 'ln(abs(x))', 'ln(k*abs(x))', 0, 'ATInt_const.', ''),
        array('Int', 'x', 'ln(abs(x))+c', 'ln(k*abs(x))', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'ln(k*x)', 'ln(k*abs(x))', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', 'x', 'ln(k*abs(x))', 'ln(k*abs(x))', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'ln(x)+ln(a)', 'ln(k*abs(x+a))', 0, 'ATInt_generic. ATInt_logabs.', 'Other logs'),
        array('Int', 'x', 'log(x)^2-2*log(c)*log(x)+k', 'ln(c/x)^2', 0, 'ATInt_EqFormalDiff.', ''),
        array('Int', 'x', 'log(x)^2-2*log(c)*log(x)+k', 'ln(abs(c/x))^2', 0, 'ATInt_generic. ATInt_logabs.', ''),
        array('Int', 'x', 'c-(log(2)-log(x))^2/2', '-1/2*log(2/x)^2', 1, 'ATInt_true_equiv.', ''),
        // In these examples there are two logarihtms.  The student should be *consistent*
        // in their use, or not, of absolute value.
        array('Int', 'x', 'log(abs(x-3))+log(abs(x+3))', 'log(abs(x-3))+log(abs(x+3))', 0, 'ATInt_const.', 'Two logs'),
        array('Int', 'x', 'log(abs(x-3))+log(abs(x+3))+c', 'log(abs(x-3))+log(abs(x+3))', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'log(abs(x-3))+log(abs(x+3))', 'log(x-3)+log(x+3)', 0, 'ATInt_const.', ''),
        array('Int', 'x', 'log(abs(x-3))+log(abs(x+3))+c', 'log(x-3)+log(x+3)', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'log(x-3)+log(x+3)', 'log(x-3)+log(x+3)', 0, 'ATInt_const.', ''),
        array('Int', 'x', 'log(x-3)+log(x+3)+c', 'log(x-3)+log(x+3)', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'log(x-3)+log(x+3)', 'log(abs(x-3))+log(abs(x+3))', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', 'x', 'log(x-3)+log(x+3)+c', 'log(abs(x-3))+log(abs(x+3))', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', 'x', 'log(abs((x-3)*(x+3)))+c', 'log(abs(x-3))+log(abs(x+3))', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', 'log(abs((x^2-9)))+c', 'log(abs(x-3))+log(abs(x+3))', 0, 'ATInt_EqFormalDiff.', ''),
        // This comes from the integral of x^3+2*x^2-3*x-2)/(x^2-4).
        array('Int', 'x', '2*log(abs(x-2))-log(abs(x+2))+(x^2+4*x)/2',
            '-log(abs(x+2))+2*log(abs(x-2))+(x^2+4*x)/2+c', 0, 'ATInt_const.', ''),
        array('Int', 'x', '-log(abs(x+2))+2*log(abs(x-2))+(x^2+4*x)/2+c',
            '-log(abs(x+2))+2*log(abs(x-2))+(x^2+4*x)/2+c', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', '-log(abs(x+2))+2*log(abs(x-2))+(x^2+4*x)/2+c',
            '-log((x+2))+2*log((x-2))+(x^2+4*x)/2', 1, 'ATInt_true_equiv.', ''),
        // Inconsistent cases. (Teacher doesn't use abs).
        array('Int', 'x', 'log(abs(x-3))+log((x+3))+c', 'log(x-3)+log(x+3)', 0,
            'ATInt_true_equiv. ATInt_logabs_inconsistent.', 'Inconsistent log(abs())'),
        array('Int', 'x', 'log((x-3))+log(abs(x+3))+c', 'log(x-3)+log(x+3)', 0,
            'ATInt_true_equiv. ATInt_logabs_inconsistent.', ''),
        array('Int', 'x', 'log((x-3))+log(abs(x+3))', 'log(x-3)+log(x+3)', 0,
            'ATInt_const. ATInt_logabs_inconsistent.', ''),
        array('Int', 'x', '2*log((x-2))-log(abs(x+2))+(x^2+4*x)/2',
            '-log(abs(x+2))+2*log(abs(x-2))+(x^2+4*x)/2', 0, 'ATInt_EqFormalDiff. ATInt_logabs. ATInt_logabs_inconsistent.', ''),
        array('Int', 't', '2*(sqrt(t)-5)-10*log((sqrt(t)-5))+c',
            '2*(sqrt(t)-5)-10*log((sqrt(t)-5))+c', 1, 'ATInt_true_equiv.', 'Significant integration constant differences'),
        array('Int', 't', '2*(sqrt(t))-10*log((sqrt(t)-5))+c',
            '2*(sqrt(t)-5)-10*log((sqrt(t)-5))+c', 1, 'ATInt_true_differentconst.', ''),
        array('Int', 't', '2*(sqrt(t)-5)-10*log((sqrt(t)-5))+c',
            '2*(sqrt(t)-5)-10*log(abs(sqrt(t)-5))+c', 0, 'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', 't', '2*(sqrt(t))-10*log(abs(sqrt(t)-5))+c',
            '2*(sqrt(t)-5)-10*log(abs(sqrt(t)-5))+c', 1, 'ATInt_true_differentconst.', ''),
        array('Int', 'x', '2*sin(x)*cos(x)', 'sin(2*x)+c', 0, 'ATInt_const.', 'Trig'),
        array('Int', 'x', '2*sin(x)*cos(x)+k', 'sin(2*x)+c', 1, 'ATInt_true.', ''),
        array('Int', 'x', '-2*cos(3*x)/3-3*cos(2*x)/2', '-2*cos(3*x)/3-3*cos(2*x)/2+c', 0, 'ATInt_const.', ''),
        array('Int', 'x', '-2*cos(3*x)/3-3*cos(2*x)/2+1', '-2*cos(3*x)/3-3*cos(2*x)/2+c', 0, 'ATInt_const_int.', ''),
        array('Int', 'x', '-2*cos(3*x)/3-3*cos(2*x)/2+c', '-2*cos(3*x)/3-3*cos(2*x)/2+c', 1, 'ATInt_true.', ''),
        array('Int', 't', '(tan(2*t)-2*t)/2',
            '-(t*sin(4*t)^2-sin(4*t)+t*cos(4*t)^2+2*t*cos(4*t)+t)/(sin(4*t)^2+cos(4*t)^2+2*cos(4*t)+1)', 0, 'ATInt_const.', ''),
        array('Int', 't', '(tan(2*t)-2*t)/2+1',
            '-(t*sin(4*t)^2-sin(4*t)+t*cos(4*t)^2+2*t*cos(4*t)+t)/(sin(4*t)^2+cos(4*t)^2+2*cos(4*t)+1)', 0, 'ATInt_const_int.', ''),
        array('Int', 't', '(tan(2*t)-2*t)/2+c',
            '-(t*sin(4*t)^2-sin(4*t)+t*cos(4*t)^2+2*t*cos(4*t)+t)/(sin(4*t)^2+cos(4*t)^2+2*cos(4*t)+1)', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'tan(x)-x+c', 'tan(x)-x', 1, 'ATInt_true.', ''),
        array('Int', 'x', '((5*%e^7*x-%e^7)*%e^(5*x))', '((5*%e^7*x-%e^7)*%e^(5*x))/25+c', 0,
            'ATInt_generic.', 'Note the difference in feedback here, generated by the options.'),
        array('Int', '[x,x*%e^(5*x+7)]', '((5*%e^7*x-%e^7)*%e^(5*x))', '((5*%e^7*x-%e^7)*%e^(5*x))/25+c', 0, 'ATInt_generic.', ''),
        // Various forms of inverse hyperbolic forms of the integrals.  Consider int(1/(x^2-a^2),x).
        array('Int', 'x', 'log(x-3)/6-log(x+3)/6+c', 'log(x-3)/6-log(x+3)/6', 1, 'ATInt_true_equiv.',
            'Inverse hyperbolic integrals'),
        array('Int', 'x', '-acoth(x/3)/3', 'log(x-3)/6-log(x+3)/6', 0, 'ATInt_const.', ''),
        array('Int', '[x, NOCONST]', '-acoth(x/3)/3', 'log(x-3)/6-log(x+3)/6', 1, 'ATInt_true.', ''),
        array('Int', 'x', '-acoth(x/3)/3+c', 'log(x-3)/6-log(x+3)/6', 1, 'ATInt_true.', ''),
        array('Int', 'x', '-acoth(x/3)/3+c', 'log(abs(x-3))/6-log(abs(x+3))/6', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'log(x-a)/(2*a)-log(x+a)/(2*a)+c', 'log(x-a)/(2*a)-log(x+a)/(2*a)', 1, 'ATInt_true_equiv.', ''),
        array('Int', 'x', '-acoth(x/a)/a+c', 'log(x-a)/(2*a)-log(x+a)/(2*a)', 1, 'ATInt_true.', ''),
        array('Int', 'x', '-acoth(x/a)/a+c', 'log(abs(x-a))/(2*a)-log(abs(x+a))/(2*a)', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'log(x-a)/(2*a)-log(x+a)/(2*a)+c', 'log(abs(x-a))/(2*a)-log(abs(x+a))/(2*a)', 0,
            'ATInt_EqFormalDiff. ATInt_logabs.', ''),
        array('Int', 'x', 'log(x-3)/6-log(x+3)/6+c', '-acoth(x/3)/3', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'log(abs(x-3))/6-log(abs(x+3))/6+c', '-acoth(x/3)/3', 1, 'ATInt_true.', ''),
        array('Int', 'x', 'log(x-3)/6-log(x+3)/6', '-acoth(x/3)/3', 0, 'ATInt_const.', ''),
        // These onse currently fail for mathematical reasons.
        array('Int', 'x', '2/3*sqrt(3)*(atan(sin(x)/(sqrt(3)*(cos(x)+1)))-(atan(sin(x)/(cos(x)+1))))+x/sqrt(3)',
            '2*atan(sin(x)/(sqrt(3)*(cos(x)+1)))/sqrt(3)', -2, 'ATInt_const.', 'Stoutemyer (currently fails)'),

        array('GT', '', '1/0', '1', -1, 'CASError: Division by zero. | ATGT_STACKERROR_SAns.', ''),
        array('GT', '', '1', '1/0', -1, 'CASError: Division by zero. | ATGT_STACKERROR_TAns.', ''),
        array('GT', '', '1', '1', 0, 'ATGT_false.', ''),
        array('GT', '', '2', '1', 1, 'ATGT_true.', ''),
        array('GT', '', '1', '2.1', 0, 'ATGT_false.', ''),
        array('GT', '', 'pi', '3', 1, 'ATGT_true.', ''),
        array('GT', '', 'pi+2', '5', 1, 'ATGT_true.', ''),
        array('GT', '', '-inf', '0', 0, 'Not number', 'Infinity'),
        array('GT', '', 'inf', '0', 0, 'Not number', ''),

        array('GTE', '', '1/0', '1', -1, 'CASError: Division by zero. | ATGTE_STACKERROR_SAns.', ''),
        array('GTE', '', '1', '1/0', -1, 'CASError: Division by zero. | ATGTE_STACKERROR_TAns.', ''),
        array('GTE', '', '1', '1', 1, 'ATGTE_true.', ''),
        array('GTE', '', '2', '1', 1, 'ATGTE_true.', ''),
        array('GTE', '', '1', '2.1', 0, 'ATGTE_false.', ''),
        array('GTE', '', 'pi', '3', 1, 'ATGTE_true.', ''),
        array('GTE', '', 'pi+2', '5', 1, 'ATGTE_true.', ''),

        array('NumRelative', '', '1/0', '0', -1, 'ATNumRelative_STACKERROR_SAns.', 'Basic tests'),
        array('NumRelative', '', '0', '1/0', -1, 'ATNumRelative_STACKERROR_TAns.', ''),
        array('NumRelative', '1/0', '0', '0', -1, 'ATNumRelative_STACKERROR_TAns.', ''),
        array('NumRelative', '', '0', '(x', -1, 'ATNumRelative_STACKERROR_TAns.', ''),
        array('NumRelative', '(x', '0', '0', -1, 'STACKERROR_OPTION.', ''),
        array('NumRelative', 'x', '1.5', '1.5', -1, 'CASError: TEST_FAILED | ATNumerical_STACKERROR_tol.', ''),
        array('NumRelative', '', 'x=1.5', '1.5', 0, 'ATNumerical_FAILED.', ''),
        array('NumRelative', '', '1.1', '1', 0, '', 'No option, so 5%'),
        array('NumRelative', '', '1.05', '1', 1, '', ''),
        array('NumRelative', '0.1', '1.05', '1', 1, '', 'Options passed'),
        array('NumRelative', '0.1', '1.05', '3', 0, '', ''),
        array('NumRelative', '0.001', '3.14', 'pi', 1, '', ''),
        array('NumRelative', '', 'inf', '0', 0, 'ATNumerical_FAILED.', 'Infinity'),
        array('NumRelative', '', '1', '[1,2]', 0, 'ATNumerical_SA_not_list.', 'Lists'),
        array('NumRelative', '', '[1,2]', '[1,2,3]', 0, 'ATNumerical_wronglen.', ''),
        array('NumRelative', '', '[1,2]', '[1,2]', 1, '', ''),
        array('NumRelative', '', '[3.141,1.414]', '[pi,sqrt(2)]', 1, '', ''),
        array('NumRelative', '0.01', '[3,1.414]', '[pi,sqrt(2)]', 0, 'ATNumerical_wrongentries SA/TA=[3.0].', ''),
        array('NumRelative', '0.01', '[3,1.414]', '{pi,sqrt(2)}', 0, 'ATNumerical_SA_not_set.', ''),
        array('NumRelative', '0.01', '{1.414,3.1}', '{pi,sqrt(2)}', 0,
            'ATNumerical_wrongentries: TA/SA=[3.14159265359], SA/TA=[3.1].', ''),
        array('NumRelative', '0.1', '{1.414,3.1}', '{pi,sqrt(2)}', 1, '', ''),

        array('NumAbsolute', '', '1/0', '0', -1, 'ATNumAbsolute_STACKERROR_SAns.', 'Basic tests'),
        array('NumAbsolute', '', '0', '1/0', -1, 'ATNumAbsolute_STACKERROR_TAns.', ''),
        array('NumAbsolute', '1/0', '0', '0', -1, 'ATNumAbsolute_STACKERROR_TAns.', ''),
        array('NumAbsolute', '', '0', '(x', -1, 'ATNumAbsolute_STACKERROR_TAns.', ''),
        array('NumAbsolute', '(x', '0', '0', -1, 'STACKERROR_OPTION.', ''),
        array('NumAbsolute', '', '1.1', '1', 0, '', 'No option, so 5%'),
        array('NumAbsolute', '', '1.05', '1', 1, '', ''),
        array('NumAbsolute', '0.1', '1.05', '1', 1, '', 'Options passed'),
        array('NumAbsolute', '0.1', '1.05', '3', 0, '', ''),
        array('NumAbsolute', '0.001', '3.14', 'pi', 0, '', ''),
        array('NumAbsolute', '0.0001', '1.41e-2', '1.41e-2', 1, '', ''),
        array('NumAbsolute', '0.0001', '0.0141', '1.41e-2', 1, '', ''),
        array('NumAbsolute', '0.0001', '0.00141', '0.00141', 1, '', ''),
        array('NumAbsolute', '0.0001', '0.00141', '1.41*10^-3', 1, '', ''),
        array('NumAbsolute', '0.0001', '1.41*10^-3', '1.41*10^-3', 1, '', ''),
        array('NumAbsolute', '0.01', '[3.141,1.414]', '[pi,sqrt(2)]', 1, '', ''),
        array('NumAbsolute', '0.01', '[3,1.414]', '[pi,sqrt(2)]', 0, 'ATNumerical_wrongentries SA/TA=[3.0].', ''),
        array('NumAbsolute', '0.01', '[3,1.414]', '{pi,sqrt(2)}', 0, 'ATNumerical_SA_not_set.', ''),
        array('NumAbsolute', '0.01', '{1.414,3.1}', '{pi,sqrt(2)}', 0,
            'ATNumerical_wrongentries: TA/SA=[3.14159265359], SA/TA=[3.1].', ''),
        array('NumAbsolute', '0.1', '{1,1.414,3.1,2}', '{1,2,pi,sqrt(2)}', 1, '', ''),

        array('NumSigFigs', '', '3.141', '3.1415927', -1, 'STACKERROR_OPTION.', 'Basic tests'),
        array('NumSigFigs', '0', '1/0', '3', -1, 'ATNumSigFigs_STACKERROR_SAns.', ''),
        array('NumSigFigs', '0', '0', '1/0', -1, 'ATNumSigFigs_STACKERROR_TAns.', ''),
        array('NumSigFigs', '1/0', '0', '0', -1, 'ATNumSigFigs_STACKERROR_TAns.', ''),
        array('NumSigFigs', '(', '0', '1', -1, 'STACKERROR_OPTION.', ''),
        array('NumSigFigs', '1', '(', '1', -1, 'ATNumSigFigs_STACKERROR_SAns.', ''),
        array('NumSigFigs', 'pi', '1', '3', -1, 'CASError: TEST_FAILED | ATNumSigFigs_STACKERROR_not_integer.', ''),
        array('NumSigFigs', '[3,x]', '1', '3', -1, 'CASError: TEST_FAILED | ATNumSigFigs_STACKERROR_not_integer.', ''),
        array('NumSigFigs', '[1,2,3]', '1', '3', -1, 'CASError: TEST_FAILED | ATNumSigFigs_STACKERROR_list_wrong_length.', ''),
        array('NumSigFigs', '', '1', '3', -1, 'STACKERROR_OPTION.', ''),
        array('NumSigFigs', '1', '1.234', '4', 0, 'ATNumSigFigs_WrongDigits. ATNumSigFigs_Inaccurate.', 'Option is a number'),
        array('NumSigFigs', '3', '3.141', '3.1415927', 0, 'ATNumSigFigs_WrongDigits.', ''),
        array('NumSigFigs', '4', '3.141', '3.1415927', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '4', '3.142', '3.1415927', 1, '', ''),
        array('NumSigFigs', '4', '3.142', 'pi', 1, '', ''),
        array('NumSigFigs', '4', 'pi', 'pi', 0, 'ATNumSigFigs_NotDecimal.', ''),
        array('NumSigFigs', '4', '3141', '3.1415927', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '3', '0.00123', '0.001234567', 1, '', ''),
        array('NumSigFigs', '3', '1.23e-3', '0.001234567', 1, '', ''),
        array('NumSigFigs', '3', '1.24e-3', '0.001234567', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '4', '1.235e-3', '0.001234567', 1, '', ''),
        array('NumSigFigs', '2', '1000', '999', 1, '', ''),
        array('NumSigFigs', '2', '1E3', '999', 1, '', ''),
        array('NumSigFigs', '1', '-100', '-149', 1, '', ''),
        array('NumSigFigs', '1', '-0.05', '-0.0499', 1, '', ''),
        array('NumSigFigs', '4', '0.1667', '0.1667', 1, '', 'Previous tricky case'),
        array('NumSigFigs', '4', '0.1666', '0.1667', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '4', '0.166', '0.1667', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '4', '0.16667', '0.1667', 0, 'ATNumSigFigs_WrongDigits.', ''),
        array('NumSigFigs', '[4,3]', '3.142', '3.1415927', 1, '', 'Mixed options'),
        array('NumSigFigs', '[4,3]', '3.143', '3.1415927', 1, '', ''),
        array('NumSigFigs', '[4,3]', '3.150', '3.1415927', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '[4,3]', '3.1416', '3.1415927', 0, 'ATNumSigFigs_WrongDigits.', ''),
        array('NumSigFigs', '[4,3]', '0.1666', '0.1667', 1, '', ''),
        array('NumSigFigs', '4', '-3.141', '-3.1415927', 0, 'ATNumSigFigs_Inaccurate.', 'Negative numbers'),
        array('NumSigFigs', '3', '-3.141', '-3.1415927', 0, 'ATNumSigFigs_WrongDigits.', ''),
        array('NumSigFigs', '4', '-3.141', '-3.1415927', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '4', '-3.142', '-3.1415927', 1, '', ''),
        array('NumSigFigs', '4', '3.142', '-3.1415927', 0, 'ATNumSigFigs_WrongSign.', ''),
        array('NumSigFigs', '4', '-3.142', '3.1415927', 0, 'ATNumSigFigs_WrongSign.', ''),
        array('NumSigFigs', '4', '-3.149', '3.1415927', 0, 'ATNumSigFigs_WrongSign. ATNumSigFigs_Inaccurate.', ''),
        /* Maxima's round() command uses Bankers' rounding, but STACK does not.
         * We actually round the teacher's answer to the specified number of SFs. */
        array('NumSigFigs', '3', '0.0499', '0.04985', 1, '', 'Round teacher answer'),
        array('NumSigFigs', '3', '0.0498', '0.04985', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '3', '0.0498', '0.04975', 1, '', ''),
        array('NumSigFigs', '3', '0.0497', '0.04975', 0, 'ATNumSigFigs_Inaccurate.', ''),
        array('NumSigFigs', '3', '0.0499', '0.0498', 0, 'ATNumSigFigs_Inaccurate.', ''),

        array('NumDecPlaces', '', '3.141', '3.1415927', -1, 'ATNumDecPlaces_STACKERROR_Option.', 'Basic tests'),
        array('NumDecPlaces', '2', '1/0', '3', -1, 'ATNumDecPlaces_NoDP. ATNumDecPlaces_STACKERROR_SAns.', ''),
        array('NumDecPlaces', '2', '0', '1/0', -1, 'ATNumDecPlaces_NoDP. ATNumDecPlaces_STACKERROR_TAns.', ''),
        array('NumDecPlaces', '1/0', '0', '0', -1, 'ATNumDecPlaces_NoDP. ATNumDecPlaces_STACKERROR_Options..', ''),
        array('NumDecPlaces', 'x', '0', '1', -1, 'ATNumDecPlaces_STACKERROR_Option.', ''),
        array('NumDecPlaces', '-1', '0', '1', -1, 'ATNumDecPlaces_STACKERROR_Option.', ''),
        array('NumDecPlaces', '0', '0', '1', -1, 'ATNumDecPlaces_STACKERROR_Option.', ''),
        array('NumDecPlaces', '(', '0', '1', -1, 'ATNumDecPlaces_STACKERROR_Option.', ''),
        array('NumDecPlaces', '1', '(', '1', -1, 'ATNumDecPlaces_STACKERROR_Option.', ''),
        array('NumDecPlaces', '2', 'x', '3.143', 0,
            'ATNumDecPlaces_NoDP. ATNumDecPlaces_Not_equiv.', 'Student\'s answer not a floating point number'),
        array('NumDecPlaces', '3', '3', '3.000', 0, 'ATNumDecPlaces_NoDP. ATNumDecPlaces_Equiv.', ''),
        array('NumDecPlaces', '2', '3.14', '3.143', 1,
            'ATNumDecPlaces_Correct. ATNumDecPlaces_Equiv.', 'Right number of places'),
        array('NumDecPlaces', '2', '3.14', '3.14', 1, 'ATNumDecPlaces_Correct. ATNumDecPlaces_Equiv.', ''),
        array('NumDecPlaces', '3', '3.140', '3.140', 1, 'ATNumDecPlaces_Correct. ATNumDecPlaces_Equiv.', ''),
        array('NumDecPlaces', '4', '3141.5972', '3141.5972', 1, 'ATNumDecPlaces_Correct. ATNumDecPlaces_Equiv.', ''),
        array('NumDecPlaces', '2', '4.14', '3.14', 0, 'ATNumDecPlaces_Correct. ATNumDecPlaces_Not_equiv.', ''),
        array('NumDecPlaces', '4', '3.1416', 'pi', 1, 'ATNumDecPlaces_Correct. ATNumDecPlaces_Equiv.', ''),
        array('NumDecPlaces', '1', '-7.3', '-7.3', 1, 'ATNumDecPlaces_Correct. ATNumDecPlaces_Equiv.', ''),
        array('NumDecPlaces', '1', '3.14', '3.143', 0,
            'ATNumDecPlaces_Wrong_DPs (2 <> 1). ATNumDecPlaces_Equiv.', 'Wrong number of places'),
        array('NumDecPlaces', '1', '3.14', '3.143', 0, 'ATNumDecPlaces_Wrong_DPs (2 <> 1). ATNumDecPlaces_Equiv.', ''),
        array('NumDecPlaces', '3', '3.14', '3.140', 0, 'ATNumDecPlaces_Wrong_DPs (2 <> 3). ATNumDecPlaces_Equiv.', ''),
        array('NumDecPlaces', '4', '7.000', '7', 0, 'ATNumDecPlaces_Wrong_DPs (3 <> 4). ATNumDecPlaces_Equiv.', ''),

        array('Units', '0', '1/0', '1', -1, 'CASError: Division by zero. | ATUnits_STACKERROR_SAns.', ''),
        array('Units', '0', '1', '1/0', -1, 'CASError: Division by zero. | ATUnits_STACKERROR_TAns.', ''),
        array('Units', '1/0', '1', '1', -1, 'CASError: Division by zero. | ATUnits_STACKERROR_TAns.', ''),
        array('Units', '0', 'x-1)^2', '(x-1)^2', -1, 'ATUnits_STACKERROR_SAns.', ''),
        array('Units', '[3,x]', '12.3*m*s^(-1)', '3*m', -1,
            'CASError: TEST_FAILED | ATNumSigFigs_STACKERROR_not_integer.', ''),
        array('Units', '[1,2,3]', '12.3*m*s^(-1)', '3*m', -1,
            'CASError: TEST_FAILED | ATNumSigFigs_STACKERROR_list_wrong_length.', ''),
        array('Units', '3', '12.3*m*s^(-1)', '{12.3*m*s^(-1)}', -1, 'CASError: TEST_FAILED | ATUnits_TA_not_expression.', ''),
        array('Units', '3', 'x=12.3*m*s^(-1)', '12.3*m*s^(-1)', 0, 'ATUnits_SA_not_expression.', ''),
        array('Units', '3', '12.3', '12.3*m', 0, 'ATUnits_SA_no_units.', 'Missing units'),
        array('Units', '3', '12', '12.3*m', 0, 'ATUnits_SA_no_units.', ''),
        array('Units', '3', '1/2', '12.3*m', 0, 'ATUnits_SA_no_units.', ''),
        array('Units', '3', 'e^(1/2)', '12.3*m', 0, 'ATUnits_SA_no_units.', ''),
        array('Units', '3', '9.81*m', '12.3', -1, 'CASError: TEST_FAILED | ATUnits_SB_no_units.', ''),
        array('Units', '3', 'm/s', '12.3*m/s', 0, 'ATUnits_SA_only_units.', 'Only units'),
        array('Units', '3', 'm', '12.3*m/s', 0, 'ATUnits_SA_only_units.', ''),
        array('Units', '3', '9.81+m/s', '9.81*m/s', 0, 'ATUnits_SA_bad_units.', 'Bad units'),
        array('Units', '3', '12.3*m/s', '12.3*m/s', 1, 'ATUnits_units_match.', 'Basic tests'),
        array('Units', '3', '12.4*m/s', '12.3*m/s', 0, 'ATNumSigFigs_Inaccurate. ATUnits_units_match.', ''),
        array('Units', '[3,2]', '12.4*m/s', '12.3*m/s', 1, 'ATUnits_units_match.', ''),
        array('Units', '[3,2]', '12.45*m/s', '12.3*m/s', 0, 'ATNumSigFigs_WrongDigits. ATUnits_units_match.', ''),
        array('Units', '[3,2]', '13.45*m/s', '12.3*m/s', 0,
            'ATNumSigFigs_WrongDigits. ATNumSigFigs_Inaccurate. ATUnits_units_match.', ''),
        array('Units', '3', '12*m/s', '12.3*m/s', 0, 'ATNumSigFigs_Inaccurate. ATUnits_units_match.', ''),
        array('Units', '3', '-9.81*m/s^2', '-9.81*m/s^2', 1, 'ATUnits_units_match.', ''),
        array('Units', '3', '-9.82*m/s^2', '-9.815*m/s^2', 1, 'ATUnits_units_match.', ''),
        array('Units', '3', '-9.81*m/s^2', '-9.815*m/s^2', 0, 'ATNumSigFigs_Inaccurate. ATUnits_units_match.', ''),
        array('Units', '3', '-9.81*m*s^(-2)', '-9.81*m/s^2', 1, 'ATUnits_units_match.', ''),
        array('Units', '3', '-9.82*m/s^2', '-9.81*m/s^2', 0, 'ATNumSigFigs_Inaccurate. ATUnits_units_match.', ''),
        array('Units', '3', '-9.81*m*s^(-2)', '-9.81*m/s^2', 1, 'ATUnits_units_match.', ''),
        array('Units', '3', '-9.81*m/s/s', '-9.81*m/s^2', 1, 'ATUnits_units_match.', ''),
        array('Units', '3', '-9.81*m/s', '-9.81*m/s^2', 0, 'ATUnits_incompatible_units. ATUnits_correct_numerical.', ''),
        array('Units', '3', '-9.81*m/s', '-9.81*m/s^2', 0, 'ATUnits_incompatible_units. ATUnits_correct_numerical.', ''),
        array('Units', '3', '9.81*m/s', '-9.81*m/s^2', 0, 'ATNumSigFigs_WrongSign. ATUnits_incompatible_units.', ''),
        array('Units', '3', '8.81*m/s', '-9.81*m/s^2', 0,
            'ATNumSigFigs_WrongSign. ATNumSigFigs_Inaccurate. ATUnits_incompatible_units.', ''),
        array('Units', '3', '8.1*m/s', '-9.81*m/s^2', 0,
            'ATNumSigFigs_WrongSign. ATNumSigFigs_Inaccurate. ATUnits_incompatible_units.', ''),
        array('Units', '3', 'm/4', '0.25*m', 1, 'ATUnits_units_match.', ''),
        array('Units', '3', 'pi*s', '3.14*s', 0, 'ATNumSigFigs_WrongDigits. ATUnits_units_match.', 'Student is too exact'),
        array('Units', '3', 'sqrt(2)*m', '1.41*m', 0, 'ATNumSigFigs_WrongDigits. ATUnits_units_match.', ''),
        array('Units', '2', '25*g', '0.025*kg', 1, 'ATUnits_compatible_units.', 'Different units'),
        array('Units', '2', '26*g', '0.025*kg', 0, 'ATNumSigFigs_Inaccurate. ATUnits_compatible_units.', ''),
        array('Units', '2', '100*g', '10*kg', 0,
            'ATNumSigFigs_WrongDigits. ATNumSigFigs_Inaccurate. ATUnits_compatible_units.', ''),
        array('Units', '2', '0.025*g', '0.025*kg', 0, 'ATUnits_compatible_units. ATUnits_correct_numerical.', ''),
        array('Units', '1', '1*Mg/10^6', '1*N*s^2/(km)', 1, 'ATUnits_compatible_units.', ''),
        array('Units', '1', '1*Mg/10^6', '1*kN*ns/(mm*Hz)', 1, 'ATUnits_compatible_units.', ''),
        array('Units', '3', '3.14*Mg/10^6', '%pi*kN*ns/(mm*Hz)', 1, 'ATUnits_compatible_units.', ''),
        array('Units', '3', '3.141*Mg/10^6', '%pi*kN*ns/(mm*Hz)', 0, 'ATNumSigFigs_WrongDigits. ATUnits_compatible_units.', ''),
        array('Units', '3', '4.141*Mg/10^6', '%pi*kN*ns/(mm*Hz)', 0,
            'ATNumSigFigs_WrongDigits. ATNumSigFigs_Inaccurate. ATUnits_compatible_units.', ''),
        array('Units', '2', '400*cc', '0.4*l', 1, 'ATUnits_compatible_units.', ''),
        array('Units', '2', '400*cm^3', '0.4*l', 1, 'ATUnits_compatible_units.', ''),
        array('Units', '2', '400*ml', '0.4*l', 1, 'ATUnits_compatible_units.', ''),
        array('Units', '2', '400*mL', '0.4*l', 1, 'ATUnits_compatible_units.', ''),
        array('Units', '4', '142.8*C', '415.9*K', -2, 'ATNumSigFigs_Inaccurate. ATUnits_incompatible_units.', 'TODO'),

        array('UnitsStrict', '2', '25*g', '0.025*kg', 0, 'ATUnits_compatible_units.', 'Differences from the Units test only'),
        array('UnitsStrict', '1', '1*Mg/10^6', '1*N*s^2/(km)', 0, 'ATUnits_compatible_units.', ''),
        array('UnitsStrict', '1', '1*Mg/10^6', '1*kN*ns/(mm*Hz)', 0, 'ATUnits_compatible_units.', ''),
        array('UnitsStrict', '3', '3.14*Mg/10^6', '%pi*kN*ns/(mm*Hz)', 0, 'ATUnits_compatible_units.', ''),
        array('UnitsStrict', '2', '400*cc', '0.4*l', 0, 'ATUnits_compatible_units.', ''),
        array('UnitsStrict', '2', '400*cm^3', '0.4*l', 0, 'ATUnits_compatible_units.', ''),
        array('UnitsStrict', '2', '400*ml', '0.4*l', 0, 'ATUnits_compatible_units.', ''),
        array('UnitsStrict', '2', '400*mL', '0.4*l', 0, 'ATUnits_compatible_units.', ''),
        array('UnitsStrict', '4', '142.8*C', '415.9*K', 0, 'ATNumSigFigs_Inaccurate. ATUnits_incompatible_units.', ''),
        array('UnitsStrict', '3', '-9.81*m/s/s', '-9.81*m/s^2', 1, 'ATUnits_units_match.', 'We are not *that* strict!'),

        array('String', '', 'Hello', 'hello', 0, '', ''),
        array('String', '', 'hello', 'hello', 1, '', ''),
        array('String', '', 'hello', 'heloo', 0, '', ''),

        array('StringSloppy', '', 'hello', 'Hello', 1, '', ''),
        array('StringSloppy', '', 'hel lo', 'Hello', 1, '', ''),
        array('StringSloppy', '', 'hello', 'heloo', 0, '', ''),

        array('RegExp', '', '3.1415927', '3.1415927', -1, 'ATRegEx_STACKERROR_Option.', ''),
        array('RegExp', '{[0-9]*\.[0-9]*}', '3.1415927', '3.1415927', 1, 'Pattern matched: 3.1415927.', ''),
        array('RegExp', '{[0-9]*\.[0-9]*}', 'cxcxcz', '3.1415927', 0, '', ''),

        array('LowestTerms', '', '1/0', '0', -1, 'CASError: Division by zero. | ATLowestTerms_STACKERROR_SAns.', ''),
        array('LowestTerms', '', '0.5', '0', 1, '', 'Mix of floats and rational numbers'),
        array('LowestTerms', '', '0.33', '0', 1, '', ''),
        array('LowestTerms', '', '2/4', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', '-1/3', '0', 1, '', 'Negative numbers'),
        array('LowestTerms', '', '1/-3', '0', 1, '', ''),
        array('LowestTerms', '', '-2/4', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', '2/-4', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', '-1/-3', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', '-2/-4', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', 'x+1/3', '0', 1, '', 'Polynomials'),
        array('LowestTerms', '', 'x+2/6', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', '2*x/4+2/6', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', '2/4*x+2/6', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', 'x-1/-4', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', 'cos(x)', '0', 1, '', 'Trig functions'),
        array('LowestTerms', '', 'cos(3/6*x)', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', 'matrix([1,2/4],[2,3])', '0', 0, 'ATLowestTerms_entries.', 'Matrices'),
        array('LowestTerms', '', 'x=1/2', '0', 1, '', 'Equations'),
        array('LowestTerms', '', '3/9=x', '0', 0, 'ATLowestTerms_entries.', ''),
        array('LowestTerms', '', 'x^2/x', '0', 1, '', 'Use predicate lowesttermsp'),
        array('LowestTerms', '', '(2*x)/(4*t)', '0', 1, '', ''),
        array('LowestTerms', '', '(2/4)*(x^2/t)', '0', 0, 'ATLowestTerms_entries.', ''),
    );

    public static function get_raw_test_data() {
        return self::$rawdata;
    }

    public static function get_available_tests() {
        $availabletests = array();
        foreach (self::$rawdata as $test) {
            $availabletests[$test[self::NAME]] = $test[self::NAME];
        }
        return $availabletests;
    }

    public static function test_from_raw($data) {
        $test = new stdClass();
        $test->name          = $data[self::NAME];
        $test->studentanswer = $data[self::SANS];
        $test->teacheranswer = $data[self::TANS];
        $test->expectedscore = $data[self::SCORE];
        $test->options       = $data[self::OPTIONS];
        $test->ansnote       = $data[self::ANSNOTE];
        $test->notes         = $data[self::NOTES];
        return $test;
    }

    public static function get_all() {
        $tests = array();
        foreach (self::$rawdata as $data) {
            $tests[] = self::test_from_raw($data);
        }
        return $tests;
    }

    public static function get_tests_for($anstest) {
        $tests = array();
        foreach (self::$rawdata as $data) {
            if ($data[self::NAME] == $anstest) {
                $tests[] = self::test_from_raw($data);
            }
        }
        return $tests;
    }

    public static function run_test($test) {
        $anst = new stack_ans_test_controller($test->name, $test->studentanswer,
                $test->teacheranswer, new stack_options(), $test->options);

        // The false clause is useful for developers to track down which test case is breaking Maxima.
        if (true) {
            $result   = $anst->do_test(); // This actually executes the answer test in the CAS.
            $errors   = $anst->get_at_errors();
            $rawmark  = $anst->get_at_mark();
            $feedback = $anst->get_at_feedback();
            $ansnote  = $anst->get_at_answernote();
        } else {
            $feedback = 'AT'.$test->name.'('.$test->studentanswer.','.$test->teacheranswer.');';
            $result   = true; // This actually executes the answer test in the CAS.
            $errors   = '';
            $rawmark  = 0;
            $ansnote  = '';
        }

        $expectednote = '';
        $passed = true;
        if (!($rawmark === $test->expectedscore)) {
            $passed = false;
        }
        if (!($ansnote === $test->ansnote)) {
            $passed = false;
            $expectednote = $test->ansnote;
        }

        // The test failed, and we expected it to fail.
        if ($errors === 'TEST_FAILED') {
            if (-1 === $test->expectedscore) {
                $passed = true;
            } else {
                $passed = false;
            }
        }
        // These tests are all expected to fail, so we make them all pass.
        if (-2 === $test->expectedscore) {
            $passed = true;
        }

        return array($passed, $errors, $rawmark, $feedback, $ansnote, $expectednote);
    }
}