pdflatex stack_publications.tex
bibtex bu1
bibtex bu2
bibtex bu3
bibtex bu4
bibtex bu5
bibtex bu6
bibtex bu7
bibtex bu8
pdflatex stack_publications.tex
pdflatex stack_publications.tex
pdflatex stack_publications.tex
