
s_test_case(rational_num_exactp(1/2), true);
s_test_case(rational_num_exactp(1/10), true);
s_test_case(rational_num_exactp(1/7), false);
s_test_case(rational_num_exactp(13/150), false);

s_test_case(rational_num_exactp(%pi^2/6), false);
s_test_case(rational_num_exactp(x), false);

s_test_case(numexactp(0.5,1/2), true);
s_test_case(numexactp(0.5,0.5), true);
s_test_case(numexactp(2/4,1/2), true);

s_test_case(numexactp(0.333,1/3), false);
s_test_case(numexactp(0.3333333333333333333333333333333333,1/3), false);
s_test_case(numexactp(1/sqrt(2),sqrt(2)/2), true);

s_test_case(num_ensure_rational(0.5*x+0.33), (1/2)*x+33/100);
s_test_case(num_ensure_rational(0.5*x-0.33), (1/2)*x+(-33/100));
s_test_case(num_ensure_rational(7/6*x+0.75*y), (7/6)*x+(3/4)*y);
s_test_case(ATEqualComAss(num_ensure_rational(7/6*x+0.75*y), (7/6)*x+(3/4)*y), [true,true,"",""]);