
s_test_case(rational_num_exactp(1/2), true);
s_test_case(rational_num_exactp(1/10), true);
s_test_case(rational_num_exactp(1/7), false);
s_test_case(rational_num_exactp(13/150), false);

s_test_case(rational_num_exactp(%pi^2/6), false);
s_test_case(rational_num_exactp(x), false);

s_test_case(numexactp(0.5,1/2), true);
s_test_case(numexactp(0.5,0.5), true);
s_test_case(numexactp(2/4,1/2), true);

s_test_case(numexactp(0.333,1/3), false);
s_test_case(numexactp(0.3333333333333333333333333333333333,1/3), false);

s_test_case(numexactp(1/sqrt(2),sqrt(2)/2), true);
