<?php
// This file is part of Stack - http://stack.maths.ed.ac.uk/
//
// Stack is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Stack is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Stack.  If not, see <http://www.gnu.org/licenses/>.

define('CLI_SCRIPT', true);

/**
 * This script executes the `genmanifest:` logic and additional documentation
 * generation for the arguments and then places the results into the normal places.
 *
 * The manifest will end up in the root of `/stack/maxima/contrib/$X.stacklib`,
 * and the docs into `/doc/en/CAS/ContribLibraries/$X.md`. $X being the first argument
 * declaring the shortname of this library.
 *
 * The arguments can be an arbirary number of `.mac` files for the logic to be included
 * and an optional `.md` file to be used as a preamble for the documentation.
 *
 * @package    qtype_stack
 * @copyright  2026 Aalto University.
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later.
 */

require(__DIR__ . '/../../../../config.php');
require_once($CFG->libdir . '/clilib.php');

require_once(__DIR__ . '/../stack/cas/contriblibrarytools.class.php');
require_once(__DIR__ . '/../stack/maximaparser/parser.options.class.php');
require_once(__DIR__ . '/../stack/maximaparser/error.interpreter.class.php');


if (count($argv) < 3) {
    echo("This command requires atleast two arguments, the first being the name of the resulting library and the remaining ones the paths to the files it consists of.");
    exit(0);
}

$name = $argv[1];

if (!preg_match('/^[a-zA-Z0-9_]+$/', $name)) { 
    echo("The library name should match the pattern '^[a-zA-Z0-9_]+$'.");
    exit(0);
}

$files = [];
for ($i = 2; $i < count($argv); $i++) {
    // Note that the genmanifest generator restricts where one can load so we use the bypass to give the content to it.
    $shortname = '/stack/maxima/' . (explode('/stack/stack/maxima/', $argv[$i], 2)[1]);
    $content = file_get_contents($argv[$i]);
    if ($content === false) {
        echo("Cannot read " . $argv[$i] . " maybe try full path?");
        exit(0);
    }
    $files[$shortname] = $content;
}

function notmd($fname) {
    return (strrpos($fname, '.md') !== mb_strlen($fname) - 3);
}

$genaddress = 'genmanifest: ' . implode(' ', array_filter(array_keys($files), 'notmd'));

// Generate the primary result, i.e., the manifest.
$manifest = stack_cas_contrib_library_tools::generate_manifest($genaddress, null, $files);

file_put_contents('../stack/maxima/contrib/' . $name . '.stacklib', json_encode($manifest, JSON_PRETTY_PRINT));

// Then the documentation.

$doc = '<!-- NOTE! This file is autogenerated, from ' . implode(' ', array_keys($files)) . ', do not edit here. -->';
$doc .= "\n# Documentation for $name contrib library\n\n";

$items = [];
$po = stack_parser_options::get_cas_config();
$po->dropcomments = false;
$parser = $po->get_parser();

// Do we have `.md` preamble(s), this should be in the order of entry...
foreach ($files as $fname => $content) {
    // Parse the files for doc comments.
    if (notmd($fname)) {
        $ast = $parser->parse($po->get_lexer($content));
        $prevcomment = null;
        $defs = [];

        // Largely the same loop as in contriblibrarytools, but dorp commentless immediately.
        foreach ($ast->items as $item) {
            if ($item instanceof MP_Statement) {
                if ($item->statement instanceof MP_Operation && $item->statement->op === ':=') {
                    // Function definition or a test definition.
                    if ($item->statement->lhs->name->value === 's_test_case') {
                        $prevcomment = null;
                    } else {
                        if ($prevcomment !== null) {
                            // Keep the previous top level comment around for processing.
                            $defs[$item->statement->lhs->name->value] = [$prevcomment, $item];
                            $prevcomment = null;
                        }
                    }
                } elseif ($item->statement instanceof MP_Operation && $item->statement->op === ':') {
                    // Definition of a variable.
                    if ($prevcomment !== null) {
                        // Keep the previous top level comment around for processing.
                        $defs[$item->statement->lhs->value] = [$prevcomment, $item];
                        $prevcomment = null;
                    }
                } else {
                    $prevcomment = null;
                }
            } else if ($item instanceof MP_Comment) {
                if (strpos($item->value, '*') === 0) {
                    $prevcomment = $item;
                } else {
                    // IF we are not the correct form of comment then the previous is not connected either.
                    $prevcomment = null;
                }
            }
        }

        // Then for each def construct the md section.
        foreach ($defs as $dname => list($comment, $code)) {
            $itemdoc = "## $dname";
            if ($code->statement->op === ':=') {
                $itemdoc .= (new MP_Group($code->statement->lhs->arguments))->toString();
            }
            $itemdoc .= "<a id='$dname'></a>\n\n";

            // Unwrap the comment.
            $com = stack_cas_contrib_library_tools::comment_body($comment->value);

            // Then clean the annotations.
            $matches = [];
            preg_match_all('#@require((\s+[a-zA-Z0-9_]+/[a-zA-Z0-9_%]+)+)#', $com, $matches);
            // Drop any @require cases.
            if (!empty($matches)) {
                foreach ($matches[0] as $match) {
                    $com = str_replace($match, ' ', $com);
                }
            }
            $r = stack_cas_contrib_library_tools::comment_annotations($com);
            $itemdoc .= trim($r['remainder'] . "\n\n" . $r['param-block'] . "\n\n" . $r['return-block']);

            $itemdoc .= "\n---\n\n\n";
            $items[$dname] = $itemdoc;
        }
    } else {
        // Do we have `.md` preamble(s), this should be in the order of entry...
        $doc .= $content;
    }
}

$doc .= "\n---\n\n";

// Then output the items in some order...
$keys = array_keys($items);
sort($keys);
foreach ($keys as $key) {
    $doc .= $items[$key];
}

// Autolink all `name` local references.
foreach ($keys as $key) {
    $doc = str_replace("`$key`", "[`$key`](#$key)", $doc);
}

// Finally dump the output.
file_put_contents('../doc/en/CAS/ContribLibraries/' . $name . '.md', $doc);
