<?php 
// This file is part of Stack - http://stack.bham.ac.uk//
//
// Stack is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Stack is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Stack.  If not, see <http://www.gnu.org/licenses/>.

require_once(dirname(__FILE__).'/../../../../config.php');
require_once($CFG->dirroot .'/course/lib.php');
require_once($CFG->libdir .'/filelib.php');

require_once(dirname(__FILE__) . '/../locallib.php');
require_once('stringutil.class.php');
require_once('options.class.php');
require_once('cas/castext.class.php');
require_once('cas/casstring.class.php');
require_once('cas/cassession.class.php');

// TODO: translate this page....

require_login();

$context = context_system::instance();
require_capability('moodle/site:config', $context);
$PAGE->set_context($context);
$PAGE->set_url('/question/type/stack/stack/test.php');

echo $OUTPUT->header();
?>
<h1>STACK healthcheck</h1>

<h2>Check LaTeX is being converted correctly</h2>
STACK generates LaTeX on the fly, and enables teachers to write LaTeX in questions.
It assumes that LaTeX will be converted by a moodle filter.  Below are samples of displayed and inline expressions in LaTeX which should be
appear correctly in your browser.  Problems here indicate incorrect moodle filter settings, not faults with STACK itself.
<h3>Single and double dollar math environments</h3>
$$ \sum_{n=1}^\infty \frac{1}{n^2} = \frac{\pi^2}{6}.$$
<br />
$ \sum_{n=1}^\infty \frac{1}{n^2} = \frac{\pi^2}{6}.$
<h3>Matching displayed and inline LaTeX tags.</h3>
\[ \sum_{n=1}^\infty \frac{1}{n^2} = \frac{\pi^2}{6}.\]
<br />
\( \sum_{n=1}^\infty \frac{1}{n^2} = \frac{\pi^2}{6}.\)
<br />
(These are currently not generated by STACK on the fly, but may be written by some question authors.)

<h2>Trying to automatically write the Maxima configuration file</h2>
<?php 
if (stack_generate_maximalocal()) {
    echo "Success!";
}


echo '<h2>Trying to automatically connect to the CAS</h2>';

echo '<p>We are trying to evaluate the following cas text:</p>';
$string = 'The derivative of @ x^4/(1+x^4) @ is $$ \frac{d}{dx} \frac{x^4}{1+x^4} = @ diff(x^4/(1+x^4),x) @ $$';
echo '<pre>'.$string.'</pre>';

$ct           = new stack_cas_text($string);
$displaytext  = $ct->get_display_castext();
$errs         = $ct->get_errors();

echo '<p>', format_text($displaytext), '</p>';
echo $errs;

echo '<p>We are trying to evaluate the following cas text:</p>';
$string = 'Two example plots below.  @plot([x^4/(1+x^4),diff(x^4/(1+x^4),x)],[x,-3,3])@  @plot([sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3])@';
echo '<pre>'.$string.'</pre>';

$ct           = new stack_cas_text($string);
$displaytext  = $ct->get_display_castext();
$errs         = $ct->get_errors();

echo '<p>', format_text($displaytext), '</p>';
echo $errs;
echo '<p>There should be two different plots.  If two identical plots are seen then this is an error in naming the plot files.  If no errors are returned, but a plot is not displayed then one of the following may help.  (i) check read permissions on the two temporary directories. (ii) change the options used by GNUPlot to create the plot.  Currently there is no web interface to these options.</p>';

echo $OUTPUT->footer();
