<?php
// This file is part of Stack - http://stack.maths.ed.ac.uk/
//
// Stack is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Stack is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Stack.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Loads and manipulates data for display on the response analysis page.
 *
 * @package    qtype_stack
 * @copyright 2024 University of Edinburgh.
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later.
 */

defined('MOODLE_INTERNAL') || die();
require_once(__DIR__ . '/questiontest.php');
require_once(__DIR__ . '/bulktester.class.php');

/**
 *
 */
class stack_question_dashboard {
    /**
     * @var object Question being analysed.
     */
    public $question;
    /**
     * @var object Question context.
     */
    public $context;
    /**
     * @var object Question usage by activity.
     */
    public $quba;
    /**
     * @var int Question slot
     */
    public $slot;
    /**
     * @var object Variant progress bar.
     */
    public $variantprogress;
    /**
     * @var object Test progress bar.
     */
    public $testprogress;

    public function __construct(object $question, int|null $seed, object $context) {
        $this->question = $question;
        $this->context = $context;
        // We hard-wire decimals to be a full stop when testing questions.
        $this->question->options->set_option('decimals', '.');
        // Create the question usage we will use.
        $this->quba = question_engine::make_questions_usage_by_activity('qtype_stack', $this->context);
        $this->quba->set_preferred_behaviour('adaptive');

        if (!is_null($seed)) {
            // This is a bit of a hack to force the question to use a particular seed,
            // even if it is not one of the deployed seeds.
            $this->question->seed = $seed;
        }
        $this->slot = $this->quba->add_question($this->question, $this->question->defaultmark);
        $this->quba->start_question($this->slot);
        // Need to save question usage to allow display of files.
        question_engine::save_questions_usage_by_activity($this->quba);

        $this->question->castextprocessor = new castext2_qa_processor($this->quba->get_question_attempt($this->slot));
    }

    public function question_details() {
        global $PAGE;
        $renderer = $PAGE->get_renderer('qtype_stack');
        $output = new StdClass();
        $output->name = $this->question->name;
        $generalfeedback = $this->question->get_generalfeedback_castext();
        $output->rendergeneralfeedback = $renderer->general_feedback($this->quba->get_question_attempt($this->slot));
        $output->generalfeedbackerr = $generalfeedback->get_errors();
        $output->seed = $this->question->seed;

        $questiondescription = $this->question->get_questiondescription_castext();
        $output->renderquestiondescription = $renderer->question_description($this->quba->get_question_attempt($this->slot));
        //Not currently displayed:
        $output->questiondescription = trim($questiondescription->get_errors());
        // Prepare the display options.
        $options = question_display_options();
        // Store a rendered version of the blank question here.
        // Runtime errors generated by test cases might change rendering later.
        $output->renderquestion = $this->quba->render_question($this->slot, $options);
        $output->questionnote = stack_ouput_castext($this->question->get_question_summary());
        $output->questionvariablevalues = $this->question->get_question_session_keyval_representation();
        $output->upgradeerrors = $this->question->validate_against_stackversion($this->context);
        $output->validationerrors = $this->question->validate_for_bulk($this->context);

        // Display a representation of the PRT for offline use.
        $offlinemaxima = [];
        foreach ($this->question->prts as $prt) {
            $obj = new stdClass();
            $obj->name = $prt->get_name();
            $obj->prt = $prt->get_maxima_representation();
            $offlinemaxima[] = $obj;
        }
        $output->prts = $offlinemaxima;
        $output->stackversion = ($this->question->stackversion == null) ?
            stack_string('stackversionnone') :
            stack_string('stackversionedited', $this->question->stackversion) .
            stack_string('stackversionnow', get_config('qtype_stack', 'version'));

        return $output;
    }

    public function create_default_test() {
        $defaulttest = stack_bulk_tester::create_default_test($this->question);
        question_bank::get_qtype('stack')->save_question_test($this->question->id, $defaulttest);
    }

    public function initial_load() {
        $output = new StdClass();
        $output->question = $this->question_details();
        $output->tests = $this->run_test_cases();
        $output->tests->generalfeedbackerr = $output->question->generalfeedbackerr;
        $output->tests->hasheadlineerror = ($output->tests->generalfeedbackerr || $output->tests->runtimeerrors) ? true : false;
        return $output;
    }

    public function create_progress_bars() {
        $this->testprogress = new progress_bar('testingquestiontests', 500, true);
        $this->variantprogress = new progress_bar('testingquestionvariants', 500, true);
    }

    public function run_test_cases() {
        $output = new StdClass();
        $output->results = [];
        $output->demotest = false;
        $output->allpassed = true;
        $output->runtimeerrors = implode('<br />', array_keys($this->question->runtimeerrors));
        $output->hasrandomvariants = $this->question->has_random_variants() ? true : false;
        // Load the list of test cases.
        $testscases = question_bank::get_qtype('stack')->load_question_tests($this->question->id);
        // Create the default test case.
        $defaulttest = null;
        $defaulttestresult = null;
        $output->hasinputs = ($this->question->inputs !== []) ? true : false;

        if (empty($testscases) && $output->hasinputs) {
            $defaulttest = stack_bulk_tester::create_default_test($this->question);
            $defaulttestresult = $defaulttest->test_question($this->question->id, $this->question->seed, $this->context);
            $output->results[stack_string('runquestiontests_example')] = $defaulttestresult;
            $output->demotest = true;
        }

        $progressevery = (int) min(max(1, count($testscases) / 200), 100);
        $a = ['total' => count($testscases), 'done' => 0];
        // Execute the tests.
        foreach ($testscases as $key => $testcase) {
            $summaryoutput = new StdClass();
            $summaryoutput->number = $testcase->testcase;
            $summaryoutput->id = 'testcase-' . $testcase->testcase . '-' . $this->question->id;
            $summaryoutput->description = $testcase->description;
            $summaryoutput->scorepass = true;
            $summaryoutput->penaltypass = true;
            $summaryoutput->notepass = true;
            $output->results[$key] = $testcase->test_question($this->question->id, $this->question->seed, $this->context);
            $currentsummary = $output->results[$key]->passed_with_reasons();
            if (!$currentsummary['passed']) {
                $output->allpassed = false;
                foreach ($currentsummary['outcomes'] as $prtoutcome) {
                    if ($summaryoutput->scorepass && str_contains($prtoutcome['reason'], stack_string('score'))) {
                        $summaryoutput->scorepass = false;
                    }
                    if ($summaryoutput->penaltypass && str_contains($prtoutcome['reason'], stack_string('penalty'))) {
                        $summaryoutput->penaltypass = false;
                    }
                    if ($summaryoutput->notepass && str_contains($prtoutcome['reason'], stack_string('answernote'))) {
                        $summaryoutput->notepass = false;
                    }
                }
            }
            $output->summary[] = $summaryoutput;
            $a['done'] += 1;
            if ($a['done'] % $progressevery == 0 || $a['done'] == $a['total']) {
                core_php_time_limit::raise(60);
                $this->testprogress->update($a['done'], $a['total'], get_string('testingquestiontests', 'qtype_stack', $a));
            }
        }
        $output->hasresults = (!empty($output->results)) ? true : false;
        return $output;
    }

    public function list_variants() {
        $output = new StdClass();
        $output->duplicateerror = false;
        $questionnotes = [];
        $output->notes = [];
        $output->deployedcount = 0;
        $output->seed = $this->question->seed;

        $output->hasrandomvariants = $this->question->has_random_variants() ? true : false;
        $output->variantmatched = !$output->hasrandomvariants;
        $output->variantdeployed = false;

        if (!empty($this->question->deployedseeds)) {
            $output->deployedcount = count($this->question->deployedseeds);
            $a = ['total' => $output->deployedcount, 'done' => 0];
            $progressevery = (int) min(max(1, count($this->question->deployedseeds) / 500), 100);
            foreach ($this->question->deployedseeds as $key => $deployedseed) {
                $variant = $this->get_variant($key, $deployedseed);
                if ($variant->iscurrentvariant) {
                    $output->variantmatched = true;
                    if ($variant->isdeployed) {
                        $output->variantdeployed = true;
                    }
                }
                $output->variantmatched = ($variant->iscurrentvariant) ? true : $output->variantmatched;
                $output->notes[] = $variant;
                $questionnotes[] = $variant->questionnote;
                $a['done'] += 1;
                if ($a['done'] % $progressevery == 0 || $a['done'] == $a['total']) {
                    core_php_time_limit::raise(60);
                    $this->variantprogress->update($a['done'], $a['total'], get_string('testingquestionvariants', 'qtype_stack', $a));
                }
            }
        } else {
            $previewurl = qbank_previewquestion\helper::question_preview_url($this->question->id, null, null, null, null, $this->context);
            $output->previewurl = $previewurl->out();
        }
        // phpcs:ignore moodle.Commenting.MissingDocblock.Function
        function sort_by_note($a1, $b1) {
            $a = $a1->questionnoterendered;
            $b = $b1->questionnoterendered;
            if ($a == $b) {
                return 0;
            }
            if ($a < $b) {
                return -1;
            }
            return 1;
        }
        usort($output->notes, 'sort_by_note');

        if (count($questionnotes) != count(array_flip($questionnotes))) {
            $output->duplicateerror = true;
        }

        return $output;
    }

    function get_variant($key, $deployedseed) {
        global $PAGE;
        $output = new StdClass();
        $output->iscurrentvariant = false;
        $output->isdeployed = false;
        $output->deployedseed = $deployedseed;
        if (!is_null($this->question->seed) && $this->question->seed == $deployedseed) {
            $output->iscurrentvariant = true;
        }

        $previewurl = qbank_previewquestion\helper::question_preview_url($this->question->id, null, null, null, $key + 1, $this->context);
        $output->previewurl = $previewurl->out();
        $qurl = new moodle_url($PAGE->url, ['seed' => $deployedseed]);
        $output->qurl = $qurl->out();

        $bulktestresults = [false, ''];
        if (optional_param('testall', null, PARAM_INT)) {
            // Bulk test all variants.
            $bulktester = new stack_bulk_tester();
            // Load the list of test cases.
            $testscases = question_bank::get_qtype('stack')->load_question_tests($this->question->id);
            $bulktestresults = $bulktester->qtype_stack_test_question($this->context, $this->question->id,
                    $testscases, 'web', $deployedseed, true);
        }

        // Print out question notes of all deployed variants.
        $qn = question_bank::load_question($this->question->id);
        $qn->seed = (int) $deployedseed;
        $cn = $qn->get_context();
        $qunote = question_engine::make_questions_usage_by_activity('qtype_stack', $cn);
        $qunote->set_preferred_behaviour('adaptive');
        $slotnote = $qunote->add_question($qn, $qn->defaultmark);
        $qunote->start_question($slotnote);
        // Check for duplicate question notes.
        $output->questionnote = $qn->get_question_summary();
        if ($output->questionnote == $this->question->get_question_summary()) {
            $output->isdeployed = true;
        }
        $output->questionnoterendered = stack_ouput_castext($output->questionnote);
        $output->bulktestresultspass = $bulktestresults[0] ? true : false;
        $output->bulktestresults = $bulktestresults[1];

        return $output;
    }
}






